# GOAL
The following cells will preprocess doc01 and doc03 for alignment along Sections (i.e. aligning Book N - Section M across the Greek and Arabic)

## Extracting Arabic Sections:

In [12]:
import re
import openiti.helper.funcs as funcs  #read_text(pth= ,remove_header=True), get_sections(), text_cleaner()
import openiti.helper.ara   as ara    #tokenize()

In [62]:
with open("../03_topics_al-dimashqi_ar-trans/Topics_Al-Dimashqi_OpenITI.txt", "r") as f:
    ara_text = f.read()

sections_ls = funcs.get_sections(ara_text)[1]
sections_ls[-10:]

[248116,
 251221,
 252788,
 253984,
 255157,
 255804,
 257819,
 263978,
 266036,
 268407]

In [68]:
sections_zip = list(zip(sections_ls[:-1], sections_ls[1:]))
sections_zip.append((sections_ls[-1], len(ara_text)))
sections_zip[-10:]

[(248116, 251221),
 (251221, 252788),
 (252788, 253984),
 (253984, 255157),
 (255157, 255804),
 (255804, 257819),
 (257819, 263978),
 (263978, 266036),
 (266036, 268407),
 (268407, 273850)]

In [143]:
ara_sections = []
for index in sections_zip:
    ara_sections.append(ara_text[index[0]:index[1]])

len(ara_sections)

106

In [159]:
import copy
ara_sections_j = copy.deepcopy(ara_sections)

In [ ]:
# ara_sections_j[0:4] = [" ".join(ara_sections_j[3])]   # merge book 1 first few lines
# ara_sections_j[18:22] = ["".join(ara_sections_j[21])] # merge book 2 first few lines
# ara_sections_j[29:33] = ["".join(ara_sections_j[32])] # merge book 3 first few lines
# ara_sections_j[35:39] = ["".join(ara_sections_j[38])] # merge book 4 first few lines
# ara_sections_j[41:45] = ["".join(ara_sections_j[44])] # merge book 5 first few lines
# ara_sections_j[50:53] = ["".join(ara_sections_j[52])] # merge book 6 first few lines
# ara_sections_j[64:68] = ["".join(ara_sections_j[67])] # merge book 7 first few lines
# ara_sections_j[69:73] = ["".join(ara_sections_j[72])] # merge book 8 first few lines

# print(ara_sections_j[21])

# TODO: remove chapter headings such as 〈قواعد السؤال〉, 〈مواضع الأشياء الواحدة〉, etc
display(ara_sections_j)

['### ||| 〈غرض هذا البحث〉\n\n# قال:\n\n# إن قصدنا فى هذا الكتاب أن نستنبط طريقا يتهيأ لنا به أن نعمل من مقدمات\n~~ذائعة قياسا فى كل مسئلة تقصد، وأن نكون — إذا أجبنا جوابا — لم نأت فيه\n~~بشىء مضاد. فينبغى أن نقول أولا ما هو القياس، وما هى أصنافه حتى يحصل لنا\n~~القياس الجدلى إذ كنا هذا القياس نلتمس فى هذا الكتاب. فنقول:\n\n# إن القياس قول إذا وضعت فيه أشياء لزم من تلك الأشياء الموضوعة شىء آخر\n~~غيرها من الاضطرار — فالبرهان هو القياس الذى يكون من مقدمات صادقة أولية،\n~~أو من مقدمات يكون مبدأ المعرفة بها قد حصل من مقدمات ما أولية صادقة.\n\n# والقياس الجدلى هو الذى ينتج من مقدمات ذائعة.\n\nPageV00P469\n\n# والمقدمات الصادقة الأولى هى التى تصدق بذاتها، لا بغيرها؛ وذلك أنه ليس\n~~ينبغى لنا أن نلتمس فى مبادئ العلوم اليقينية «لم الشىء»، لكن ينبغى أن\n~~يكون كل واحد من مبادئ العلوم اليقينية صادقا بنفسه. والمقدمات الذائعة هى\n~~التى يظنها جميع الناس أو أكثرهم أو جماعة الفلاسفة أو أكثرهم أو المشهورون\n~~منهم والذين فى غاية النباهة.\n\n# والقياس الممارى هو الذى يكون من مقدمات ذائعة فى الظاهر، وليست ذائعة\n~~على الحقيقة؛ أو الذى يكون فى الظاهر من مقدمات ذائعة أو من ذائعة فى\n~~الظاهر، لأنه ليس كل ما كان ذائعا فى الظاهر فهو أيضا ذائعا. وذلك أنه ليس\n~~شىء من الأشياء التى يقال فيها إنها ذائعة يكون تصوره فى جميع حالاته مموها\n~~كما يعرض فى مبادئ أقاويل الممارين، لأن طبيعة الكذب تتبين فيها على المكان\n~~فى أكثر الأمر لمن معه أدنى فطنة، فضلا عن غيره. فالأول من القياسين\n~~المماريين اللذين وصفنا ينبغى أن يسمى قياسا. وأما الثانى فينبغى أن يسمى\n~~مماريا، فأما 〈أن يسمى〉 قياسا، فلا؛ لأنه فى الظاهر قياس، إلا أنه ليس ينتج.\n\nPageV00P470\n\n# وها هنا أيضا غير هذه القياسات المذكورة كلها، وهى المغالطات التى تكون ms001\n~~من الأشياء التى تخص بعض العلوم، بمنزلة ما يعرض فى الهندسة وما جانسها من\n~~العلوم. فإنه قد يشبه أن يكون هذا الصنف يخالف القياسات التى وصفنا، لأن\n~~الذى يرسم شكلا باطلا ليس يعمل قياسا من مقدمات صادقة أولية، ولا من مقدمات\n~~ذائعة: إذ كان ليس يدخل فى الحد، وذلك أنه ليس يقتضب ما يظنه جميع الناس\n~~ولا ما يراه أكثرهم، ولا ما يظنه الفلاسفة أو أكثرهم أو المشهورون جدا\n~~منهم، لكنه يعمل القياس من المقدمات التى تخص الصناعة، إلا أنها ليست\n~~صادقة. لأنه إذا رسم أنصاف الدوائر على غير ما ينبغى، أو أخرج بعض الخطوط\n~~على غير طريق إخراجها، استعمل المغالطة.\n\n# فلينزل أن أنواع القياسات، إذا حصلناها على طريق الرسم، هى هذه التى\n~~وصفنا. وبالجملة، نقول إن هذا مبلغ ما نريد تحصيله فى جميع ما وصفنا وما\n~~سنصفه من بعد، لأنه ليس قصدنا فى شىء منها استيفاء القول المستقصى. ولكن\n~~الذى نريد أن نصفه من أمرها على طريق الرسم لما رأينا فيه من الغناء\n~~والكفاية فى هذا الطريق الذى نحونا نحوه، وهو أن يكون يتهيأ لنا أن نتعرف\n~~كل واحد منها كيفما كان.\n\nPageV00P471\n\n',
 '### || [chapter 2: I 2] 〈فائدة الجدل〉\n\n# ويتبع ما وصفنا أن نذكر الأشياء التى ينتفع فيها بهذا الكتاب: كم هى؟ وما هى؟\n\n# فنقول إنه ينتفع به فى ثلاثة أشياء: فى الرياضة، وفى المناظرة، وفى علوم\n~~الفلسفة. والأمر فى أن هذا الكتاب نافع فى الرياضة ظاهر بين من هذا، وذلك\n~~أنه إذا كان لنا طريق نسلكه أمكننا بأسهل مأخذ أن نحتج فيما نقصد للحجة\n~~فيه. — فأما منفعته فى المناظرة فمن قبل أنا إذا أحصينا آراء الجمهور كانت\n~~مخاطبتنا إياهم من الآراء التى تخصهم، لا من الأشياء الغريبة، لننقلهم عما\n~~نراهم لا يصيبون القول فيه. — فأما منفعته فى علوم الفلسفة فلأنا إذا قدرنا\n~~أن نتشكك فى الأمرين جميعا، سهل علينا فى كل واحد من الأمور أن ندرك الحق\n~~والباطل.\n\n# وقد ننتفع به أيضا فى أوائل كل واحد من العلوم، وذلك أنه ليس ms002 يمكننا أن\n~~نقول فيها شيئا من الأشياء من المبادئ التى تخص العلم الذى ننحو نحوه،\n~~لأنها مبادئ أولى الجميع. فأما من الأشياء الذائعة فى كل واحد فواجب ضرورة\n~~أن نتكلم فيها. فإن هذا المعنى أخص الأشياء وأليقها بصناعة المنطق، إذ كان\n~~لها بما هى عليه من الفحص والتنقير طريق إلى مبادئ جميع الصناعات.\n\nPageV00P472\n\n',
 '### || [chapter 3: I 3] 〈المهارة فى الجدل〉\n\n# وإنما يحصل لنا من هذه الصناعة على الكمال متى كانت حالنا فيها على مثال\n~~حالنا فى الخطابة والطب وفى أمثالها من القوى، أعنى أن يكون إنما يفعل ما\n~~يريد أن يفعله من الأشياء التى يمكن أن نفعل. فإن الخطيب ليس يقنع من كل\n~~وجه، ولا الطبيب يعيد الصحة من كل وجه، لكن متى لم يغفلا شيئا مما يمكنهما\n~~ألا يغفلاه قلنا إنهما قد حصلا الصناعة على الكفاية.\n\n',
 '### || [chapter 4: I 4] 〈نظرة عامة إلى عناصر البرهان الجدلى〉\n\n# فأولا ينبغى أن ننظر من ماذا تتقوم هذه الصناعة. فإنا إذا حصلناكم هى،\n~~وما حالها، وأى الأقاويل هى، وكيف نستنبطها، كنا قد حصلنا ما قصدنا له على\n~~الكفاية. فنقول: إن الأشياء التى منها الأقاويل و〈الأشياء التى〉 فيها\n~~القياسات متساوية فى العدد وواحدة بعينها. وذلك أن الأقاويل تحدث عن\n~~المقدمات، والأشياء التى فيها تكون القياسات هى المسائل. 〈وكل مقدمة〉 وكل\n~~مسئلة، فإما أن تكون خاصة أو جنسا أو عرضا. وذلك أن الفصل لما كان جنسيا،\n~~وجب أن يرتبه مع الجنس؛ ولأن من الخاصة ما يدل على ما الشىء، ومنها ما لا\n~~يدل على ذلك، PageV00P473 فلنقسمها إلى الجزئين الموصوفين كليهما، ولنسم\n~~الدال على ما هو الشىء «حدا»، ونسمى الجزء الثانى بالاسم العام لهما، أعنى\n~~خاصة. فبين مما قلنا أنه يلزم أن يكون جميعها على حسب هذه القسمة أربعة:\n~~إما حدا، وإما خاصة، وإما جنسا، وإما عرضا. وليس ينبغى أن يظن بنا أحد أنا\n~~نقول إن كل واحد من هذه إذا قيل على حدته فهو إما مسئلة وإما مقدمة، لكنا\n~~تقول إن من هذه تحدث المقدمات والمسائل. — والمسئلة إنما تخالف ms003 المقدمة\n~~بالجهة. وذلك أن هذا القول إذا قيل على هذه الجهة: ليس قولنا: حى — مشاء —\n~~ذو رجلين حدا للإنسان؟ — تكون مقدمة. وكذلك إذا قيل: أليس الحى جنسا\n~~للإنسان؟ كان مقدمة. فإن قيل: هل قولنا: حى — مشاء — ذو رجلين، — حد\n~~للإنسان؟ وهل قولنا: «الحى» جنس للإنسان أم لا؟ — كان مسئلة. وعلى ذلك\n~~المثال يجرى الأمر فى سائر الأشياء الأخر. فبالواجب صارت المسائل والمقدمات\n~~متساوية فى العدد، وذلك أنك قد تعمل من كل مقدمة مسئلة إذا نقلتها عن جهتها.\n\n',
 '### || [chapter 5: I 5] 〈دراسة عناصر الجدل تفصيلا〉\n\n# وينبغى أن نقول: ما الحد؟ وما الخاصة؟ وما الجنس؟ وما العرض؟\n\n# فالحد هو القول الدال على ماهية الشىء. وقد يوصف أيضا بأنه قول مكان اسم،\n~~أو قول مكان قول، لأنه قد يمكننا أن نحد بعض الأشياء PageV00P474 التى\n~~يستدل عليها بقول. فأما الذين يجعلون الصفة بالاسم كيفما كان فمن البين\n~~أنهم ليس يوفون تحديد المعنى، لأن كل تحديد فهو قول ما. إلا أنه ينبغى أن\n~~نجعل ما يجرى هذا المجرى داخلا فى باب الحد، مثل قولنا: اللائق جميل. وكذلك\n~~قولنا: هل الحس والعلم شىء واحد بعينه؟ أم أحدهما غير الآخر؟ فإن أكثر\n~~البحث أيضا إنما يكون فى الحدود عن: هل الشىء واحد بعينه، أو هو غير؟\n~~وبالجملة، فينبغى أن نسمى جميع الأشياء التى هى والحدود تحت صناعة واحدة\n~~بعينها الداخلة فى باب الحدود.\n\n# والأمر فى أن جميع ما قلناه الآن حاله هذه الحال بين من ذاته. فإنا إذا\n~~قدرنا أن نقول الشىء بعينه والغير، أمكننا الاحتجاج فى الحدود أيضا بهذا\n~~الوجه بعينه. وذلك أنا إذا بينا أنه ليس فيها الشىء بغيته، نكون قد أبطلنا\n~~التحديد. غير أن المعنى الذى وصفنا الآن لا ينعكس، لأنه ليس يكفى فى تثبيت\n~~الحد أن نبين أن الشىء بعينه فيه موجود. فأما فى إبطاله فقد يكفى أن نبين\n~~أنه ليس فيه الشىء بعينه.\n\n# والخاصة هى ما لم يدل على ماهية الشىء وكان موجودا للأمر وحده وراجعا\n~~عليه فى الحمل. مثال ذلك: قبول علم ms004 النحو للإنسان: فإنه مهما كان الإنسان\n~~موجوا، فالقابل لعلم النحو موجود. ومهما كان القابل لعلم PageV00P485 النحو\n~~موجودا، فالإنسان موجود. وذلك أنه ليس أحد يقول إن الخاصة يمكن أن توجد\n~~لغير ما هى له خاصة، بمنزلة النوم للإنسان، لا ولو اتفق أن يوجد له وحده فى\n~~وقت من الأوقات. فإن قيل لما يجرى هذا المجرى خاصة، فليس يقال له خاصة، على\n~~الإطلاق، لكن فى بعض الأوقات وبالإضافة إلى شىء. فإن وجود الشىء يمنة إنما\n~~يقال إنه خاصة له فى بعض الأوقات؛ وذو الرجلين فإنما يقال إنه خاصة\n~~بالإضافة إلى شىء — بمنزلة ما هو للإنسان بالإضافة إلى الفرس وإلى الكلب.\n~~والأمر بين فى أنه ليس شىء مما يمكن أن يوجد لشىء آخر غير الشىء الذى هو له\n~~يرجع عليه بالتكافؤ فى الحمل. وذلك أنه ليس يجب ضرورة متى وجد شىء ينام أن\n~~يكون الإنسان موجودا.\n\n# والجنس هو المحمول على كثيرين مختلفين بالنوع من طريق ما هو. وينبغى أن\n~~يقال إن الأشياء التى تحمل من طريق ما هو — وهى التى يليق بنا أن نأتى بها\n~~إذا سئلنا عن الشىء الموضوع: ما هو؟ كما يليق بنا إذا سئلنا عن الإنسان ما\n~~〈هو〉 أن نقول إنه حيوان. فأما ما يسأل عنها هل هى فى جنس واحد بعينه وهى\n~~مختلفة، أم فى جنسين مختلفين، فإنما هى فى مذهب الجنس، لأن ما يجرى هذا\n~~المجرى يدخل هو والجنس فى طريق واحد بعينه. وذلك أنا إذا قلنا إن الحيوان\n~~جنس للإنسان، وكذلك للثور، نكون قد قلنا PageV00P476 إن هذين داخلان فى جنس\n~~واحد بعينه. فإن نحن بينا أنه جنس لأحدهما، غير جنس للآخر، نكون قد قلنا إن\n~~هذين ليسا بداخلين فى جنس واحد بعينه. والعرض هو ما لم يوجد واحدا من هذه:\n~~لا حدا، ولا خاصة، ولا جنسا، وهو موجود فى الشىء، أو هو الذى يمكن أن يوجد\n~~لواحد بعينه كائنا ما كان، وألا يوجد — بمنزلة الجلوس، فإنه يمكن أن يوجد\n~~لواحد بعينه كائنا ما كان وألا يوجد؛ وكذلك ms005 الأبيض، فإنه ليس مانع يمنع أن\n~~يكون شىء واحد بعينه مرة أبيض، ومرة غير أبيض. والثانى من حدى العرض أجود\n~~من الأول، لأن الأول إذا قيل احتاج من يريد أن يفهمه أن يتقدم فيعلم ما\n~~الحد والجنس والخاصة. فأما الثانى فكامل بنفسه، يستغنى به على حدته فى\n~~معرفة الموصوف ما هو. وينبغى أن نضيف إلى العرض مقايسات الأشياء بعضها إلى\n~~بعض كيفما كانت إذا قيلت من العرض، مثال ذلك قولنا: أيهما آثر؟: الجميل، أو\n~~النافع؟ وأى المذهبين ألذ: الذى تستعمل فيه الفضيلة، أو الذى ينهمك فيه\n~~الشهوات؟ وغير ذلك مما يقال على هذا المثال. فإن البحث فى أمثال هذه كلها\n~~إنما هو عن: أى الاثنين يكون لزوم المحمول به أحرى؟\n\n# وبين من هذه أنه ليس يمنع مانع فى بعض الأوقات وبالإضافة إلى شىء أن يكون\n~~العرض خاصة: 〈بمنزلة〉 الجلوس الذى هو عرض. فمتى ألفى PageV00P477 إنسان\n~~جالسا وحده، صار الجلوس له فى ذلك الوقت حينئذ خاصة. وإذا لم يكن جالسا هو\n~~وحده، فالجلوس له خاصة بالإضافة إلى ما ليس هو جالسا. فليس يمنع إذا مانع\n~~من أن يكون العرض فى بعض الأوقات وبالإضافة إلى شىء، خاصة. فأما خاصة على\n~~الإطلاق، فلا يكون.\n\n',
 '### || [chapter 6: I 6] 〈دراسة الألفاظ المحمولة〉\n\n# وليس ينبغى أن يذهب علينا أن جميع ما يقال فى الخاصة والجنس والعرض قد\n~~يليق به أن يقال فى الحدود. وذلك أنا إذا بينا أن الحد ليس هو لما تحت الحد\n~~وحده كالحال فى الخاصة أيضا، أو أن الموصوف فى الحد ليس هو جنسا، أو أن\n~~شيئا ما قد وصف فى القول لا يوجد له، كالذى يقال فى العرض، نكون قد أبطلنا\n~~التحديد. فيجب — بحسب القول الموصوف آنفا — أن يكون جميع ما عددنا داخلا فى\n~~مذهب الحدود بضرب من الضروب.\n\n# ولكن ليس ينبغى لهذا السبب أن نلتمس فى جميعها طريقاواحدا كليا، لأن هذا\n~~أمر ليس يسهل وجوده. وإن وجد، كأن فى غاية الإغماض ولم ينتفع به فى هذا\n~~الكتاب. وإذا وصف طريق خاص فى ms006 كل واحد من الأجناس المحصلة، صارت صفة ما\n~~يقصد له منها سهلة من الأشياء التى تخص واحدا واحدا فينبغى أن نقسمها على\n~~طريق الرسم كما قلنا قبل. فأما الباقية فيجب PageV00P478 أن نضم كل واحد\n~~منها إلى أخص الأشياء به ونسميها الداخلة فى باب الحد والداخلة فى باب\n~~الجنس. ونكاد أن نكون قد أضفنا ما وصفناه إلى كل واحد منها.\n\n',
 '### || [chapter 7: I 7] 〈على كم نحو يقال الشىء بعينه〉\n\n# وينبغى قبل كل شىء أن نلخص أمر الشىء بعينه على كم نحو يقال فنقول: إنه\n~~يظن بالشىء بعينه إذا أخذ على طريق الرسم أنه ينقسم على ثلاثة أنحاء. وذلك\n~~أنا قد اعتدنا 〈أن نقول〉 فى الشىء بعينه إنه كذلك: إما فى العدد، وإما فى\n~~النوع، وإما فى الجنس. أما فى العدد فمتى كانت الأسماء له كثيرة والمعنى\n~~واحدا بعينه، بمنزلة الثوب والرداء. وأما فى النوع فجميع الأشياء التى هى\n~~كثيرة، إلا أنها غير مختلفة فى النوع — بمنزلة إنسان مع إنسان، وفرس مع\n~~فرس. وذلك أن جميع الأشياء التى هى تحت نوع واحد يقال فيها إنها شىء واحد\n~~بعينه فى النوع. وكذلك جميع الأشياء التى تحت جنس واحد يقال فيها إنها شىء\n~~واحد بعينه فى الجنس — بمنزلة الإنسان والفرس: فإنهما شىء واحد بعينه فى\n~~الجنس. وقد يظن بالماء الذى 〈هو〉 خارج من عين واحدة بعينها إذا قيل فيه إنه\n~~واحد بعينه أن بينه وبين الأصناف التى ذكرت فرقا ما؛ وليس الأمر كذلك، لا\n~~بل ينبغى أن يرتب هذا الصنف أيضا فى الأشياء التى يقال فيها إنها شىء\n~~PageV00P479 واحد بعينه فى النوع كيفما كان ذلك، فإن أمثال هذه الأشياء\n~~كلها يشبه أن تكون متجانسة ويشبه بعضها بعضا. وذلك أن كل ما قد يقال إنه،\n~~وكل ماء، شىء واحد بعينه فى النوع لما بينها من المشابهة، والماء الذى يخرج\n~~من عين واحدة بعينها ليس يختلف بشىء آخر إلا بشدة المشابهة. ولذلك ليس يفرق\n~~بينه وبين ما يقال فيه إنه تحت نوع واحد كيفما قيل ذلك. والشىء ms007 بعينه فى\n~~العدد قد يظن بالإجماع عند الناس كلهم أنه أولى ما يوصف بذلك. وقد جرت\n~~العادة بأن هذا المعنى يقال على أنحاء كثيرة، أحقها وأولادها بالتقديم ما\n~~وصف واحدا بعينه بالاسم أو بالحد، كالحال فى الثوب والرداء، وفى قولنا\n~~للإنسان: حى مشاء ذو رجلين. والنحو الثانى ما كان كذلك بالخاصة، كالحال فى\n~~قولنا: قابل للعلم — فى الإنسان، وفى قولنا: سام إلى فوق بالطبع — فى\n~~النار. والنحو الثالث ما وصف بذلك من العرض كقولنا: جالس، أو موسيقار — فى\n~~سقراط. فإن جميع هذه من شأنها أن تدل على الواحد فى العدد.\n\n# ومن أبلغ ما وقف الإنسان منه على صحة ما قيل فى هذا الموضع تغيير\n~~الألقاب. وذلك أنا مرارا كثيرة إذا هممنا بأن نأمر بأن يدعى إلينا بإنسان\n~~من قوم جلوس باسمه، غيرنا اسمه إذا اتفق أن يكون الذى يأمره كان يعرف اسمه\n~~وجعلناه من العرض، من قبل أنه لذلك أفهم وأمرناه أن يدعو لنا بالجالس أو\n~~المناظر لظننا بأن الأمر بين فى أن الدلالة بالاسم وبالعرض واحدة بعينها.\n\nPageV00P480\n\n',
 '### || [chapter 8: I 8] 〈براهين الألفاظ المحمولة〉\n\n# فالشىء بعينه ينقسم كما قلنا على ثلاثة أنحاء: فأول التصديق — بأن\n~~الأقاويل إنما هى مما وصفنا أولا وبما وصفنا وفيما وصفنا — هو الذى يكون\n~~بالاستقراء. وذلك أن باحثا إن بحث عن واحدة واحدة من المقدمات والمسائل\n~~يبين له أنها تحدث: إما عن الحد، وإما عن الخاصة، وإما عن الجنس، وإما عن العرض.\n\n# والتصديق الآخر هو الذى يكون بالقياس. وذلك أنه واجب ضرورة أن يكون كل\n~~محمول على شىء إما أن يرجع عليه بالحمل، وإما ألا يرجع عليه. فإن كان يرجع\n~~عليه فهو إما حد، وإما خاصة. وذلك أنه إن كان يدل على ماهية الشىء فهو حد؛\n~~وإن لم يكن يدل على ماهيته فهو خاصة، إذ كانت الخاصة ما رجع على الشىء\n~~بالحمل من غير أن يدل على ماهيته. وإن كان لا يرجع على الشىء بالحمل فهو\n~~إما من الأشياء التى تقال فى حد الموضوع، أو ليس منها. ms008 فإن كان مما يقال فى\n~~الحد فهو إما جنس وإما فصل، لأن الحد مأخوذ من جنس وفصول. وإن لم يكن مما\n~~يقال فى الحد فمن البين أنه عرض، لأنا قد قلنا إن العرض هو ماليس بحد ولا\n~~خاصة ولا جنس، وهو موجود فى الشىء الذى هو له عرض.\n\nPageV00P481\n\n',
 '### || [chapter 9: I 9] 〈المقولات وصلتها بالألفاظ المحمولة〉\n\n# وبعد هذه الأشياء ينبغى أن نحد أجناس المقولات التى فيها توجد هذه\n~~الأربعة التى وصفنا. فنقول: إن عدتها عشرة: ما هو الشىء؛ والكم؛ والكيف؛\n~~والمضاف؛ وأين؛ ومتى؛ والنصبة؛ وله؛ ويفعل؛ وينفعل. وذلك أن العرض والجنس\n~~والخاصة والحد أبدا فى واحد من هذه العشر مقولات يوجد. فإن جميع المقدمات\n~~المأخوذة من هذه إما أن تدل على ما الشىء، أو على كيف أو على كم، أو على\n~~واحدة من سائر المقولات الأخر. وبين من هذه أن الإنسان إذا دل على:«ما\n~~الشىء» فمرة يدل على جوهر، ومرة على كم، ومرة على كيف، ومرة على واحدة من\n~~المقولات الأخر. وذلك أن واضعا لو وضع إنسانا ثم قال: إن هذا الموضوع إنسان\n~~هو أو حى، فإنما يقول ما هو، وإنما يدل على جوهر. وإذا وضع لونا أبيض وقال:\n~~إن هذا الموضوع أبيض هو أو لون، فإنما يقول ما هو، وإنما يدل على كيف. وإذا\n~~وضع عظما مقدار ذراع فقال: إن هذا الموضوع ذو ذراع أو عظم، فإنما يقول ما\n~~هو، وإنما يدل على كم. وكذلك يخرج الأمر فى الأخر: وذلك أن كل واحد من\n~~أمثال هذه إنما كان هو يقال على نفسه أو الجنس يقال عليه، فإنما يدل على ما\n~~هو؛ وإن كان يقال على غيره فليس يدل على ما هو، لكن على كم وكيف أو واحدة\n~~من المقولات الأخر.— فهذه هى الأشياء التى فيها ومنها الأقاويل، وهذه عدتها.\n\nPageV00P482\n\n',
 '### || [chapter 10: I 10] 〈القضايا الجدلية〉\n\n# وبعد هذا ينبغى أن نقول كيف نقتضب الأشياء التى بها نستنبط ونستخرج.\n~~ولنحدد أولا المقدمة المنطقية ما هى، والمسئلة المنطقية ما هى. وليس يجب أن\n~~نضع كل مقدمة ms009 منطقية، ولا كل مسئلة منطقية. وذلك أنه ليس أحد ممن له عقل\n~~يقدم ما لا يراه أحد، ولا يسأل عما هو ظاهر للناس كلهم أو لأكثرهم، لأن هذا\n~~ليس فيه شك، وذاك لا يضعه أحد من الناس.\n\n# والمقدمة المنطقية هى مسئلة ذائعة إما عند جميع الناس، أو عند اكثرهم، أو\n~~عند جماعة الفلاسفة، أو عند أكثرهم، أو عند أهل النباهة منهم، من غير أن\n~~تكون مبدعة. وذلك أن للإنسان أن يضع ما يراه الفلاسفة متى لم يكن مضادا\n~~لآراء الجمهور والأشياء الشبيهة بالذائعة والمضادة أيضا التى يظن بها أنها\n~~ذائعة إذا قدمت على جهة التناقض.\n\n# وجميع الآراء أيضا الموجودة فى الصناعات المستخرجة قد تكون مقدمات\n~~منطقية، وذلك أنه إن كان قولنا إن العلم بالمتضادات واحد بعينه ذائعا،\n~~فقولنا إن الحس بالمتضادات واحد بعينه يرى أنه ذائع. وإن كان قولنا إن كان\n~~يوجد نحو واحد بالعدد ذائعا، فقولنا يوجد غناء واحد PageV00P483 بالعدد\n~~ذائع. وإن كان قولنا: يوجد نحو أكثر من واحد ذائعا، فقولنا: يوجد غناء أكثر\n~~من واحد، ذائع. وذلك أن هذه كلها يشبه أن تكون متشابهة متجانسة. وكذلك\n~~الأشياء المضادة للذائعة إذا قدمت على جهة التناقض ظهرت ذائعة، لأن قولنا:\n~~ينبغى أن نحسن إلى الأصدقاء إن كان ذائعا، فإن قولنا أيضا: لا ينبغى أن\n~~نسىء إليهم، ذائع. فأما ضد هذا القول فهو قولنا: ينبغى أن نسىء بالأصدقاء.\n~~فأما المناقض له فولنا: ليس ينبغى أن نسىء بهم. وكذلك قولنا: إن كان ينبغى\n~~أن نحسن إلى الأصدقاء فلا ينبغى أن نحسن إلى الأعداء. وكذلك يجرى الأمر فى\n~~الأشياء الأخر. وقد يظهر بالمقايسة أن الضد على الضد أيضا ذائع، مثال ذلك:\n~~إن كان ينبغى أن نحسن إلى الأصدقاء فقد ينبغى أن نسىء بالأعداء. وقد يظهر\n~~أن الإحسان إلى الأصدقاء ضد الإساءة بالأعداء. وسننظر فى هذا الأمر هل هو\n~~على الحقيقة هكذا، أم لا — فيما نقوله فى المتضادات.\n\n# ومن البين أن الآراء التى توجد فى الصناعات قد تكون مقدمات منطقية، لأن\n~~لواضع أن يضع ms010 الأشياء التى يعتقدها الحذاق بهذه الصنائع: مثل الطبيب فيما\n~~يوجد فى صناعة الطب، والمهندس فيما يوجد فى صناعة الهندسة؛ وكذلك الأمر فى\n~~الصنائع الأخر.\n\nPageV00P484\n\n',
 '### || [chapter 11: I 11] 〈المسئلة الجدلية والوضع الجدلى〉\n\n# والمسئلة المنطقية هى طلب معنى ينتفع به فى الإيثار للشىء والهرب منه، أو\n~~فى الحق والمعرفة — إما هو بنفسه وإما من قبل أنه معين على شىء آخر من\n~~أمثال هذه، أو ما يكون الفلاسفة تعتقد أيضا فيه لا كذا ولا كذا، وإما ما\n~~يكونون يعتقدون فيه ضد ما يعتقده الجمهور، وإما ما يكون كل واحد من\n~~الفريقين يضاد صاحبه فيما يعتقد فيه. وذلك أن بعض المسائل ينتفع بمعرفته فى\n~~الإيثار للشىء أو فى الهرب منه — مثال ذلك قولنا: هل اللذة مؤثرة، أم لا.\n~~وبعضها ينتفع به فى العلم به فقط، مثل قولنا: هل العالم أزلى، أم لا؟\n~~وبعضها لا ينتفع بها أنفسها فى شىء من هذين المعنيين، بل هى معينة على بعض\n~~هذه. وذلك أن كثيرا من الأشياء ليس نريد أن نعلمها هى فى أنفسها، بل إنما\n~~نريدها لغيرها، أعنى لنعلم بها أشياء أخر. وهاهنا أيضا مسائل لها قياسات\n~~متضادة، وذلك أنه قد يقع فيها شك: هل هى كذا، أم ليس هى كذا؟ من قبل أن فى\n~~كلا المعنيين أقاويل مقعنة، والتى ليس لنا أيضا فيها حجة إذ هى عظيمة لظننا\n~~بأن قولنا فيها: لم ذلك؟ عسر — مثال ذلك: هل العالم أزلى، أم لا؟ فإن\n~~لمطالب أن يطالب بأمثال هذه. فقد حصلت المسائل والمقدمات كما قلنا.\n\nPageV00P485\n\n# والوضع هو رأى مبدع لبعض المشهورين بالفلسفة — مثال ذلك ما قاله أنطستانس\n~~أنه ليس لأحد أن يناقض، وما قاله ايراقليطس من أن كل شىء يتحرك، وما قاله\n~~مالسس من أن الكل واحد. وذلك أن من الحزن أن يهتم الإنسان بقول شاذ يحكم\n~~بضد الآراء، أو يهتم بالأشياء التى فيها قول مضاد للآراء — مثال ذلك القول\n~~بأن ليس كل موجودا إما مكونا وإما أزليا، كما تقول السوفسطائية إن الذى هو\n~~موسيقار ويصير نحويا ليس هو ms011 متكونا ولا أزليا. وذلك أن هذا، وإن كان لا\n~~يراه أحد، فقد يظن به أنه شىء لأن فيه قولا.\n\n# فالوضع أيضا مسئلة، وليس كل مسئلة وضعا، لأن بعض المسائل يجرى مجرى ما لا\n~~يعتقد فيها أن الأمر كذا أو كذا، والأمر فى أن الوضع مسألة ما، بين، وذلك\n~~أنه واجب ضرورة مما قلنا إما أن يتشكك الجمهور فى الوضع على الفلاسفة، وإما\n~~أن يتشك أحد الفريقين: أيهما كان، على أنفسهم، من قبل أن الوضع رأى ما مبدع.\n\n# وتكاد أن تكون المسائل الجدلية فى هذا الموضع تسمى أوضاعا؛ وليس فى ذلك\n~~خلاف كيفما قيل، لأنا لسنا نريد بقسمتها أن نخترع لها اسما، لكن الذى نريد\n~~〈هو〉 ألا يذهب علينا فصولها أيما هى.\n\nPageV00P486\n\n# وليس ينبغى لنا أن نبحث عن كل مسئلة، ولا عن كل وضع؛ لكن يجب أن يكون\n~~بحثنا عما شك فيه شاك مما يحتاج فيه إلى قول، لا إلى عقوبة أو حس. وذلك أن\n~~الذين يشكون فيقولون: هل ينبغى أن يعبد الله، أم لا؟ وأن يجب أن يكرم\n~~الوالدان أم لا؟ يحتاجون إلى عقوبة. والذين يشكون فيقولون: هل الثلج أبيض،\n~~أم لا؟ — يحتاجون إلى حس. ولا يجب أن يتشكك أيضا فيما كان البرهان عليه\n~~قريبا جدا، ولا فيما كان البرهان عليه بعيدا جدا، فإن ذاك ليس فيه شك، وهذا\n~~أبعد كثيرا من أن يكون مقدمة يرتاض بها.\n\n',
 '### || [chapter 12: I 12] 〈البرهان والاستقراء الجدليان〉\n\n# وإذ قد لخصنا هذه الأشياء فينبغى أن نميز وننظر كم أنواع الأقاويل\n~~المنطقية. فنقول: إن أنواعها نوعان: أحدهما استقراء النظائر، والآخر قياس.\n~~وقد قلنا ما القياس فيما تقدم.— و〈أما〉 الاستقراء فهو الطريق من الأمور\n~~الجزئية إلى الأمر الكلى — مثال ذلك أنه إن كان الربان الحاذق هو الأفضل،\n~~فالأمر كذلك فى الفارس؛ فيصير بالجملة الحاذق فى كل واحد من الصنائع هو\n~~الأفضل. والاستقراء هو أكثر إقناعا وأبين وأعرف فى الحس، وهو مشترك\n~~للجمهور. فأما القياس فهو أشد إلزأما للحجة وابلغ عند المناقضين.\n\nPageV00P487\n\n',

In [178]:
ara_sections_clean = []

for s in ara_sections_j:
    clean_text = funcs.text_cleaner(s)
    ara_sections_clean.append(clean_text.strip())

print(len(ara_sections_clean))
display(ara_sections_clean[:4])

83

['غرض هذا البحث قال ان قصدنا في هذا الكتاب ان نستنبط طريقا يتهيا لنا به ان نعمل من مقدمات ذاءعة قياسا في كل مسءلة تقصد وان نكون اذا اجبنا جوابا لم نات فيه بشء مضاد فينبغي ان نقول اولا ما هو القياس وما هي اصنافه حتي يحصل لنا القياس الجدلي اذ كنا هذا القياس نلتمس في هذا الكتاب فنقول ان القياس قول اذا وضعت فيه اشياء لزم من تلك الاشياء الموضوعة شء اخر غيرها من الاضطرار فالبرهان هو القياس الذي يكون من مقدمات صادقة اولية او من مقدمات يكون مبدا المعرفة بها قد حصل من مقدمات ما اولية صادقة والقياس الجدلي هو الذي ينتج من مقدمات ذاءعة والمقدمات الصادقة الاولي هي التي تصدق بذاتها لا بغيرها وذلك انه ليس ينبغي لنا ان نلتمس في مبادء العلوم اليقينية لم الشء لكن ينبغي ان يكون كل واحد من مبادء العلوم اليقينية صادقا بنفسه والمقدمات الذاءعة هي التي يظنها جميع الناس او اكثرهم او جماعة الفلاسفة او اكثرهم او المشهورون منهم والذين في غاية النباهة والقياس المماري هو الذي يكون من مقدمات ذاءعة في الظاهر وليست ذاءعة علي الحقيقة او الذي يكون في الظاهر من مقدمات ذاءعة او من ذاءعة في الظاهر لانه ليس كل ما كان ذاءعا في الظاهر فهو ايضا ذاءعا وذلك انه ليس شء من الاشياء التي يقال فيها انها ذاءعة يكون تصوره في جميع حالاته مموها كما يعرض في مبادء اقاويل الممارين لان طبيعة الكذب تتبين فيها علي المكان في اكثر الامر لمن معه ادني فطنة فضلا عن غيره فالاول من القياسين المماريين اللذين وصفنا ينبغي ان يسمي قياسا واما الثاني فينبغي ان يسمي مماريا فاما ان يسمي قياسا فلا لانه في الظاهر قياس الا انه ليس ينتج وها هنا ايضا غير هذه القياسات المذكورة كلها وهي المغالطات التي تكون من الاشياء التي تخص بعض العلوم بمنزلة ما يعرض في الهندسة وما جانسها من العلوم فانه قد يشبه ان يكون هذا الصنف يخالف القياسات التي وصفنا لان الذي يرسم شكلا باطلا ليس يعمل قياسا من مقدمات صادقة اولية ولا من مقدمات ذاءعة اذ كان ليس يدخل في الحد وذلك انه ليس يقتضب ما يظنه جميع الناس ولا ما يراه اكثرهم ولا ما يظنه الفلاسفة او اكثرهم او المشهورون جدا منهم لكنه يعمل القياس من المقدمات التي تخص الصناعة الا انها ليست صادقة لانه اذا رسم انصاف الدواءر علي غير ما ينبغي او اخرج بعض الخطوط علي غير طريق اخراجها استعمل المغالطة فلينزل ان انواع القياسات اذا حصلناها علي طريق الرسم هي هذه التي وصفنا وبالجملة نقول ان هذا مبلغ ما نريد تحصيله في جميع ما وصفنا وما سنصفه من بعد لانه ليس قصدنا في شء منها استيفاء القول المستقصي ولكن الذي نريد ان نصفه من امرها علي طريق الرسم لما راينا فيه من الغناء والكفاية في هذا الطريق الذي نحونا نحوه وهو ان يكون يتهيا لنا ان نتعرف كل واحد منها كيفما كان',
 'فاءدة الجدل ويتبع ما وصفنا ان نذكر الاشياء التي ينتفع فيها بهذا الكتاب كم هي وما هي فنقول انه ينتفع به في ثلاثة اشياء في الرياضة وفي المناظرة وفي علوم الفلسفة والامر في ان هذا الكتاب نافع في الرياضة ظاهر بين من هذا وذلك انه اذا كان لنا طريق نسلكه امكننا باسهل ماخذ ان نحتج فيما نقصد للحجة فيه فاما منفعته في المناظرة فمن قبل انا اذا احصينا اراء الجمهور كانت مخاطبتنا اياهم من الاراء التي تخصهم لا من الاشياء الغريبة لننقلهم عما نراهم لا يصيبون القول فيه فاما منفعته في علوم الفلسفة فلانا اذا قدرنا ان نتشكك في الامرين جميعا سهل علينا في كل واحد من الامور ان ندرك الحق والباطل وقد ننتفع به ايضا في اواءل كل واحد من العلوم وذلك انه ليس يمكننا ان نقول فيها شيءا من الاشياء من المبادء التي تخص العلم الذي ننحو نحوه لانها مبادء اولي الجميع فاما من الاشياء الذاءعة في كل واحد فواجب ضرورة ان نتكلم فيها فان هذا المعني اخص الاشياء واليقها بصناعة المنطق اذ كان لها بما هي عليه من الفحص والتنقير طريق الي مبادء جميع الصناعات',
 'المهارة في الجدل وانما يحصل لنا من هذه الصناعة علي الكمال متي كانت حالنا فيها علي مثال حالنا في الخطابة والطب وفي امثالها من القوي اعني ان يكون انما يفعل ما يريد ان يفعله من الاشياء التي يمكن ان نفعل فان الخطيب ليس يقنع من كل وجه ولا الطبيب يعيد الصحة من كل وجه لكن متي لم يغفلا شيءا مما يمكنهما الا يغفلاه قلنا انهما قد حصلا الصناعة علي الكفاية',
 'نظرة عامة الي عناصر البرهان الجدلي فاولا ينبغي ان ننظر من ماذا تتقوم هذه الصناعة فانا اذا حصلناكم هي وما حالها واي الاقاويل هي وكيف نستنبطها كنا قد حصلنا ما قصدنا له علي الكفاية فنقول ان الاشياء التي منها الاقاويل و الاشياء التي فيها القياسات متساوية في العدد وواحدة بعينها وذلك ان الاقاويل تحدث عن المقدمات والاشياء التي فيها تكون القياسات هي المساءل وكل مقدمة وكل مسءلة فاما ان تكون خاصة او جنسا او عرضا وذلك ان الفصل لما كان جنسيا وجب ان يرتبه مع الجنس ولان من الخاصة ما يدل علي ما الشء ومنها ما لا يدل علي ذلك فلنقسمها الي الجزءين الموصوفين كليهما ولنسم الدال علي ما هو الشء حدا ونسمي الجزء الثاني بالاسم العام لهما اعني خاصة فبين مما قلنا انه يلزم ان يكون جميعها علي حسب هذه القسمة اربعة اما حدا واما خاصة واما جنسا واما عرضا وليس ينبغي ان يظن بنا احد انا نقول ان كل واحد من هذه اذا قيل علي حدته فهو اما مسءلة واما مقدمة لكنا تقول ان من هذه تحدث المقدمات والمساءل والمسءلة انما تخالف المقدمة بالجهة وذلك ان هذا القول اذا قيل علي هذه الجهة ليس قولنا حي مشاء ذو رجلين حدا للانسان تكون مقدمة وكذلك اذا قيل اليس الحي جنسا للانسان كان مقدمة فان قيل هل قولنا حي مشاء ذو رجلين حد للانسان وهل قولنا الحي جنس للانسان ام لا كان مسءلة وعلي ذلك المثال يجري الامر في ساءر الاشياء الاخر فبالواجب صارت المساءل والمقدمات متساوية في العدد وذلك انك قد تعمل من كل مقدمة مسءلة اذا نقلتها عن جهتها']

## Extracting Greek Sections:

In [24]:
with open("../01_topics_aristotle/aristotle_topics_greek.txt", 'r') as f:
    grc_text = f.read()

grc_text[:100]

pattern = r"\[\d+\.\d+\]"

re.findall(pattern, grc_text)

['[1.1]',
 '[1.2]',
 '[1.3]',
 '[1.4]',
 '[1.5]',
 '[1.6]',
 '[1.7]',
 '[1.8]',
 '[1.9]',
 '[1.10]',
 '[1.11]',
 '[1.12]',
 '[1.13]',
 '[1.14]',
 '[1.15]',
 '[1.16]',
 '[1.17]',
 '[1.18]',
 '[2.1]',
 '[2.2]',
 '[2.3]',
 '[2.4]',
 '[2.5]',
 '[2.6]',
 '[2.7]',
 '[2.8]',
 '[2.9]',
 '[2.10]',
 '[2.11]',
 '[3.1]',
 '[3.2]',
 '[3.3]',
 '[3.4]',
 '[3.5]',
 '[3.6]',
 '[4.1]',
 '[4.2]',
 '[4.3]',
 '[4.4]',
 '[4.5]',
 '[4.6]',
 '[5.1]',
 '[5.2]',
 '[5.3]',
 '[5.4]',
 '[5.5]',
 '[5.6]',
 '[5.7]',
 '[5.8]',
 '[5.9]',
 '[6.1]',
 '[6.2]',
 '[6.3]',
 '[6.4]',
 '[6.5]',
 '[6.6]',
 '[6.7]',
 '[6.8]',
 '[6.9]',
 '[6.10]',
 '[6.11]',
 '[6.12]',
 '[6.13]',
 '[6.14]',
 '[7.1]',
 '[7.2]',
 '[7.3]',
 '[7.4]',
 '[7.5]',
 '[8.1]',
 '[8.2]',
 '[8.3]',
 '[8.4]',
 '[8.5]',
 '[8.6]',
 '[8.7]',
 '[8.8]',
 '[8.9]',
 '[8.10]',
 '[8.11]',
 '[8.12]',
 '[8.13]',
 '[8.14]']

In [72]:
grc_sections = re.split(pattern, grc_text)

print(len(grc_sections))
display(grc_sections)

84

['ΑΡΙΣΤΟΤΕΛΟΥΣ ΤΟΠΙΚΑ\n\nBekker edition (Oxford University Press, 1837)\nSource: OpenGreekAndLatin First1KGreek (CC BY-SA 4.0)\n============================================================\n\nΤΟΠΙΚΩΝ Α\n\n',
 '\nΤΟΠΙΚΩΝ Α.\nἩ ΜΕΝ πρόθεσις τῆς πραγματείας μέθοδον εὑρεῖν, ἀφ᾿ ἧς δυνησόμεθα συλλογίζεσθαι\nπερὶ παντὸς τοῦ προτεθέντος προβλήματος ἐξ ἐνδόξων, καὶ αὐτοὶ λόγον ὑπέχοντες\nμηθὲν ἐροῦμεν ὑπεναντίον. Πρῶτον οὖν ῥητέον τί ἐστι συλλογισμὸς καὶ τίνες\nαὐτοῦ διαφοραί, ὅπως ληφθῇ ὁ διαλεκτικὸς συλλογισμός· τοῦτον γὰρ ζητοῦμεν κατὰ\nτὴν προκειμένην πραγματείαν.\n\nἜστι δὴ συλλογισμὸς λόγος ἐν ᾧ τεθέντων τινῶν ἕτερόν τι τῶν κειμένων ἐξ ἀνάγκης\nσυμβαίνει διὰ τῶν κειμένων. Ἀπόδειξις μὲν οὖν ἐστίν, ὅταν ἐξ ἀληθῶν καὶ πρώτων ὁ\nσυλλογισμὸς ᾖ, ἢ ἐκ τοιούτων ἃ διά τινων πρώτων καὶ ἀληθῶν τῆς περὶ αὐτὰ\nγνώσεως τὴν ἀρχὴν εἴληφεν· διαλεκτικὸς δὲ συλλογισμὸς ὁ ἐξ ἐνδόξων\nσυλλογιζόμενος. Ἔστι δὲ ἀληθῆ μὲν καὶ πρῶτα τὰ μὴ δι᾿ ἑτέρων ἀλλὰ δι᾿ αὑτῶν\nἔχοντα τὴν πίστιν· οὐ δεῖ γὰρ ἐν ταῖς ἐπιστημονικαῖς ἀρχαῖς ἐπιζητεῖσθαι τὸ\nδιὰ τί, ἀλλ᾿ ἑκάστην τῶν ἀρχῶν αὐτὴν καθ᾿ ἑαυτὴν εἶναι πιστήν. Ἔνδοξα δὲ τὰ\nδοκοῦντα πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς σοφοῖς, καὶ τούτοις ἢ πᾶσιν ἢ τοῖς\nπλείστοις ἢ τοῖς μάλιστα γνωρίμοις καὶ ἐνδόξοις. Ἐριστικὸς δ᾿ ἐστὶ\nσυλλογισμὸς ὁ ἐκ φαινομένων ἐνδόξων, μὴ ὄντων δέ, καὶ ὁ ἐξ ἐνδόξων ἢ φαινομένων\nἐνδόξων φαινόμενος. Οὐ γὰρ πᾶν τὸ φαινόμενον ἔνδοξον καὶ ἔστιν ἔνδοξον. Οὐθὲν\nγὰρ τῶν λεγομένων ἐνδόξων ἐπιπόλαιον ἔχει παντελῶς τὴν φαντασίαν, καθὰ περὶ\nτὰς τῶν ἐριστικῶν λόγων ἀρχὰς συμβέβηκεν ἔχειν· παραχρῆμα γὰρ καὶ ὡς ἐπὶ τὸ πολὺ\nτοῖς καὶ μικρὰ συνορᾶν δυναμένοις κατάδηλος ἐν αὐτοῖς ἡ τοῦ ψεύδους\nἐστὶ φύσις. Ὁ μὲν οὖν πρότερος τῶν ῥηθέντων ἐριστικῶν συλλογισμῶν καὶ\nσυλλογισμὸς λεγέσθω, ὁ δὲ λοιπὸς ἐριστικὸς μὲν συλλογισμός, συλλογισμὸς δ᾿ οὔ,\nἐπειδὴ φαίνεται μὲν συλλογίζεσθαι, συλλογίζεται δ᾿ οὔ.\n\nἜτι δὲ παρὰ τοὺς εἰρημένους ἅπαντας συλλογισμοὺς οἱ ἐκ τῶν περί τινας ἐπιστήμας\nοἰκείων γινόμενοι παραλογισμοί, καθάπερ ἐπὶ τῆς γεωμετρίας καὶ τῶν ταύτῃ συγγενῶν\nσυμβέβηκεν ἔχειν. Ἔοικε γὰρ ὁ τρόπος οὗτος διαφέρειν τῶν εἰρημένων\nσυλλογισμῶν· οὔτε γὰρ ἐξ ἀληθῶν καὶ πρώτων συλλογίζεται ὁ ψευδογραφῶν, οὔτ᾿ ἐξ\nἐνδόξων. Εἰς γὰρ τὸν ὅρον οὐκ ἐμπίπτει· οὔτε γὰρ τὰ πᾶσι δοκοῦντα λαμβάνει\nοὔτε τὰ τοῖς πλείστοις οὔτε τὰ τοῖς σοφοῖς, καὶ τούτοις οὔτε τὰ πᾶσιν οὔτε τοῖς\nπλείστοις οὔτε τοῖς ἐνδοξοτάτοις, ἀλλ᾿ ἐκ τῶν οἰκείων μὲν τῇ ἐπιστήμῃ λημμάτων,\nοὐκ ἀληθῶν δὲ τὸν συλλογισμὸν ποιεῖται. Τῷ γὰρ ἢ τὰ ἡμικύκλια περιγράφειν μὴ\nὡς δεῖ, ἢ γραμμάς τινας ἄγειν μὴ ὡς ἂν ἀχθείησαν, τὸν παραλογισμὸν ποιεῖται.\n\nΕἴδη μὲν οὖν τῶν συλλογισμῶν, ὡς τύπῳ περιλαβεῖν, ἔστω τὰ εἰρημένα. Καθόλου δ᾿\nεἰπεῖν περὶ πάντων τῶν εἰρημένων καὶ τῶν μετὰ ταῦτα ῥηθησομένων, ἐπὶ τοσοῦτον\nἡμῖν διωρίσθω, διότι περὶ οὐδενὸς αὐτῶν τὸν ἀκριβῆ λόγον ἀποδοῦναι\nπροαιρούμεθα, ἀλλ᾿ ὅσον τύπῳ περὶ αὐτῶν βουλόμεθα διελθεῖν, παντελῶς ἱκανὸν\nἡγούμενοι κατὰ τὴν προκειμένην μέθοδον τὸ δύνασθαι γνωρίζειν ὁπωσοῦν ἕκαστον\nαὐτῶν.\n\n',
 '\nἙπόμενον δ᾿ ἂν εἴη τοῖς εἰρημένοις εἰπεῖν πρὸς πόσα τε καὶ τίνα χρήσιμος ἡ\nπραγματεία. Ἔστι δὴ πρὸς τρία, πρὸς γυμνασίαν, πρὸς τὰς ἐντεύξεις, πρὸς τὰς κατὰ\nφιλοσοφίαν ἐπιστήμας. Ὅτι μὲν οὖν πρὸς γυμνασίαν χρήσιμος, ἐξ αὐτῶν\nκαταφανές ἐστι· μέθοδον γὰρ ἔχοντες ῥᾷον περὶ τοῦ προτεθέντος\nἐπιχειρεῖν δυνησόμεθα. Πρὸς δὲ τὰς ἐντεύξεις, διότι τὰς τῶν πολλῶν κατηριθμημένοι\nδόξας οὐκ ἐκ τῶν ἀλλοτρίων ἀλλ᾿ ἐκ τῶν οἰκείων δογμάτων ὁμιλήσομεν πρὸς αὐτούς,\nμεταβιβάζοντες ὅ τι ἂν μὴ καλῶς φαίνωνται λέγειν ἡμῖν. Πρὸς δὲ τὰς κατὰ\nφιλοσοφίαν ἐπιστήμας, ὅτι δυνάμενοι πρὸς ἀμφότερα διαπορῆσαι ῥᾷον ἐν ἑκάστοις\nκατοψόμεθα τἀληθές τε καὶ τὸ ψεῦδος. Ἔτι δὲ πρὸς τὰ πρῶτα τῶν περὶ ἑκάστην\nἐπιστήμην ἀρχῶν. Ἐκ μὲν γὰρ τῶν οἰκείων τῶν κατὰ τὴν προτεθεῖσαν ἐπιστήμην ἀρχῶν\nἀδύνατον εἰπεῖν τι περὶ αὐτῶν, ἐπειδὴ πρῶται αἱ ἀρχαὶ ἁπάντων εἰσί, διὰ δὲ\nτῶν περὶ ἕκαστα ἐνδόξων ἀνάγκη περὶ αὐτῶν διελθεῖν. Τοῦτο δ᾿ ἴδιον ἢ μάλιστα\nοἰκεῖον τῆς διαλεκτικῆς ἐστίν· ἐξεταστικὴ γὰρ οὖσα πρὸς τὰς ἁπασῶν τῶν μεθόδων\nἀρχὰς ὁδὸν ἔχει.\n\n',
 '\nἝξομεν δὲ τελέως τὴν μέθοδον, ὅταν ὁμοίως ἔχωμεν ὥσπερ ἐπὶ ῥητορικῆς καὶ\nἰατρικῆς καὶ τῶν τοιούτων δυνάμεων. Τοῦτο δ᾿ ἐστὶ τὸ ἐκ τῶν ἐνδεχομένων ποιεῖν ἃ\nπροαιρούμεθα. Οὔτε γὰρ ὁ ῥητορικὸς ἐκ παντὸς τρόπου πείσει, οὔθ᾿ ὁ ἰατρικὸς\nὑγιάσει· ἀλλ᾿ ἐὰν τῶν ἐνδεχομένων μηδὲν παραλείπῃ, ἱκανῶς αὐτὸν ἔχειν τὴν\nἐπιστήμην φήσομεν.\n\n',
 '\nΠρῶτον οὖν θεωρητέον ἐκ τίνων ἡ μέθοδος. Εἰ δὴ λάβοιμεν πρὸς πόσα καὶ ποῖα καὶ\nἐκ τίνων οἱ λόγοι, καὶ πῶς τούτων εὐπορήσομεν, ἔχοιμεν ἂν ἱκανῶς τὸ προκείμενον.\nἜστι δ᾿ ἀριθμῷ ἴσα καὶ ταὐτά, ἐξ ὧν τε οἱ λόγοι καὶ περὶ ὧν οἱ συλλογισμοί.\nΓίνονται μὲν γὰρ οἱ λόγοι ἐκ τῶν προτάσεων· περὶ ὧν δὲ οἱ συλλογισμοί, τὰ\nπροβλήματά ἐστι. Πᾶσα δὲ πρότασις καὶ πᾶν πρόβλημα ἢ γένος ἢ ἴδιον ἢ\nσυμβεβηκὸς δηλοῖ· καὶ γὰρ τὴν διαφορὰν ὡς οὖσαν γενικὴν ὁμοῦ τῷ γένει\nτακτέον. Ἐπεὶ δὲ τοῦ ἰδίου τὸ μὲν τὸ τί ἦν εἶναι σημαίνει, τὸ δ᾿ οὐ σημαίνει,\nδιῃρήσθω τὸ ἴδιον εἰς ἄμφω τὰ προειρημένα μέρη, καὶ καλείσθω τὸ μὲν τὸ\nτί ἦν εἶναι σημαῖνον ὅρος, τὸ δὲ λοιπὸν κατὰ τὴν κοινὴν περὶ αὐτῶν\nἀποδοθεῖσαν ὀνομασίαν προσαγορευέσθω ἴδιον. Δῆλον οὖν ἐκ τῶν εἰρημένων ὅτι\nκατὰ τὴν νῦν διαίρεσιν τέτταρα τὰ πάντα συμβαίνει γίνεσθαι, ἢ ἴδιον ἢ ὅρον ἢ\nγένος ἢ συμβεβηκός. Μηδεὶς δ᾿ ἡμᾶς ὑπολάβῃ λέγειν ὡς ἕκαστον τούτων καθ᾿\nαὑτὸ λεγόμενον πρότασις ἢ πρόβλημά ἐστιν, ἀλλ᾿ ὅτι ἀπὸ τούτων καὶ τὰ προβλήματα\nκαὶ αἱ προτάσεις γίνονται. Διαφέρει δὲ τὸ πρόβλημα καὶ ἡ πρότασις τῷ τρόπῳ.\nΟὕτω μὲν γὰρ ῥηθέντος, ἆρά γε τὸ ζῷον πεζὸν δίπουν ὁρισμός ἐστιν ἀνθρώπου;\nκαὶ ἆρά γε τὸ ζῷον γένος ἐστὶ τοῦ ἀνθρώπου; πρότασις γίνεται. Ἐὰν δέ, πότερον τὸ\nζῷον πεζὸν δίπουν ὁρισμός ἐστιν ἀνθρώπου ἢ οὔ; καὶ πότερον τὸ ζῷον γένος\nἐστίν; πρόβλημα γίνεται. Ὁμοίως δὲ καὶ ἐπὶ τῶν ἄλλων. Ὅστ᾿ εἰκότως ἴσα τῷ ἀριθμῷ\nτὰ προβλήματα καὶ αἱ προτάσεις εἰσίν. Ἀπὸ πάσης γὰρ προτάσεως πρόβλημα\nποιήσεις μεταβάλλων τῷ τρόπῳ.\n\n',
 '\nΛεκτέον δὲ τί ὅρος, τί ἴδιον, τί γένος, τί συμβεβηκός. Ἔστι δ᾿ ὅρος μὲν λόγος ὁ\nτὸ τί ἦν εἶναι σημαίνων. Ἀποδίδοται δὲ ἢ λόγος ἀντ᾿ ὀνόματος ἢ λόγος ἀντὶ λόγου·\nδυνατὸν γὰρ καὶ τῶν ὑπὸ λόγου τινὰ σημαινομένων ὁρίσασθαι. Ὅσοι δ᾿ ὁπωσοῦν\nὀνόματι τὴν ἀπόδοσιν ποιοῦνται, δῆλον ὡς οὐκ ἀποδιδόασιν οὗτοι τὸν τοῦ πράγματος\nὁρισμόν, ἐπειδὴ πᾶς ὁρισμὸς λόγος τίς ἐστιν. Ὁρικὸν μέντοι καὶ τὸ τοιοῦτον\nθετέον, οἷον ὅτι καλόν ἐστι τὸ πρέπον. Ὁμοίως δὲ καὶ τὸ πότερον ταὐτὸν\nαἴσθησις καὶ ἐπιστήμη ἢ ἕτερον· καὶ γὰρ περὶ τοὺς ὁρισμούς, πότερον ταὐτὸν ἢ\nἕτερον, ἡ πλείστη γίνεται διατριβή. Ἁπλῶς δὲ ὁρικὰ πάντα λεγέσθω τὰ ὑπὸ τὴν\nαὐτὴν ὄντα μέθοδον τοῖς ὁρισμοῖς. Ὅτι δὲ πάντα τὰ νῦν ῥηθέντα τοιαῦτ᾿ ἐστί, δῆλον\nἐξ αὐτῶν. Δυνάμενοι γὰρ ὅτι ταὐτὸν καὶ ὅτι ἕτερον διαλέγεσθαι, τῷ αὐτῷ\nτρόπῳ καὶ πρὸς τοὺς ὁρισμοὺς ἐπιχειρεῖν εὐπορήσομεν· δείξαντες γὰρ ὅτι οὐ\nταὐτόν ἐστιν ἀνῃρηκότες ἐσόμεθα τὸν ὁρισμόν. Οὐ μὴν ἀντιστρέφει γε τὸ νῦν ῥηθέν·\nοὐ γὰρ ἱκανὸν πρὸς τὸ κατασκευάσαι τὸν ὁρισμὸν τὸ δεῖξαι ταὐτὸν ὄν. Πρὸς μέντοι\nτὸ ἀνασκευάσαι αὔταρκες τὸ δεῖξαι ὅτι οὐ ταὐτόν.\n\nἼδιον δ᾿ ἐστὶν ὃ μὴ δηλοῖ μὲν τὸ τί ἦν εἶναι, μόνῳ δ᾿ ὑπάρχει καὶ\nἀντικατηγορεῖται τοῦ πράγματος, οἷον ἴδιον ἀνθρώπου τὸ γραμματικῆς εἶναι\nδεκτικόν· εἰ γὰρ ἄνθρωπός ἐστι, γραμματικῆς δεκτικός ἐστι, καὶ εἰ γραμματικῆς\nδεκτικός ἐστιν, ἄνθρωπός ἐστιν. Οὐθεὶς γὰρ ἴδιον λέγει τὸ ἐνδεχόμενον ἄλλῳ\nὑπάρχειν, οἷον τὸ καθεύδειν ἀνθρώπῳ, οὐδ᾿ ἂν τύχῃ κατά τινα χρόνον μόνῳ ὑπάρχον.\nΕἰ δ᾿ ἄρα τι καὶ λέγοιτο τῶν τοιούτων ἴδιον, οὐχ ἁπλῶς ἀλλὰ ποτὲ ἢ πρός τι\nἴδιον ῥηθήσεται· τὸ μὲν γὰρ ἐκ δεξιῶν εἶναι ποτὲ ἴδιόν ἐστι, τὸ δὲ δίπουν πρός τι\nἴδιον τυγχάνει λεγόμενον, οἷον τῷ ἀνθρώπῳ πρὸς ἵππον καὶ κύνα. Ὅτι δὲ τῶν\nἐνδεχομένων ἄλλῳ ὑπάρχειν οὐθὲν ἀντικατηγορεῖται, δῆλον· οὐ γὰρ ἀναγκαῖον,\nεἴ τι καθεύδει, ἄνθρωπον εἶναι.\n\nΓένος δ᾿ ἐστὶ τὸ κατὰ πλειόνων καὶ διαφερόντων τῷ εἴδει ἐν τῷ τί ἐστι\nκατηγορούμενον. Ἐν τῷ τί ἐστι δὲ κατηγορεῖσθαι τὰ τοιαῦτα λεγέσθω, ὅσα ἁρμόττει\nἀποδοῦναι ἐρωτηθέντας τί ἐστι τὸ προκείμενον, καθάπερ ἐπὶ τοῦ ἀνθρώπου\nἁρμόττει, ἐρωτηθέντα τί ἐστι τὸ προκείμενον, εἰπεῖν ὅτι ζῷον. Γενικὸν δὲ καὶ\nτὸ πότερον ἐν τῷ αὐτῷ γένει ἄλλο ἄλλῳ ἢ ἐν ἑτέρῳ. Καὶ γὰρ τὸ τοιοῦτον ὑπὸ τὴν\nαὐτὴν μέθοδον πίπτει τῷ γένει· διαλεχθέντες γὰρ ὅτι τὸ ζῷον γένος τοῦ\nἀνθρώπου, ὁμοίως δὲ καὶ τοῦ βοός, διειλεγμένοι ἐσόμεθα ὅτι ἐν τῷ αὐτῷ γένει. Ἐὰν\nδὲ τοῦ μὲν ἑτέρου δείξωμεν ὅτι γένος ἐστί, τοῦ δὲ ἑτέρου ὅτι οὐκ ἔστι,\nδιειλεγμένοι ἐσόμεθα ὅτι οὐκ ἐν τῷ αὐτῷ γένει ταῦτ᾿ ἐστίν.\n\nΣυμβεβηκὸς δέ ἐστιν ὃ μηδὲν μὲν τούτων ἐστί, μήτε ὅρος μήτε ἴδιον μήτε γένος,\nὑπάρχει δὲ τῷ πράγματι, καὶ ὃ ἐνδέχεται ὑπάρχειν ὁτῳοῦν ἑνὶ καὶ τῷ αὐτῷ καὶ μὴ\nὑπάρχειν, οἷον τὸ καθῆσθαι ἐνδέχεται ὑπάρχειν τινὶ τῷ αὐτῷ καὶ μὴ ὑπάρχειν.\nὉμοίως δὲ καὶ τὸ λευκόν· τὸ γὰρ αὐτὸ οὐθὲν κωλύει ὁτὲ μὲν λευκὸν ὁτὲ δὲ μὴ\nλευκὸν εἶναι. Ἔστι δὲ τῶν τοῦ συμβεβηκότος ὁρισμῶν ὁ δεύτερος βελτίων· τοῦ μὲν\nγὰρ πρώτου ῥηθέντος ἀναγκαῖον, εἰ μέλλει τις συνήσειν, προειδέναι τί ἐστιν\nὅρος καὶ γένος καὶ ἴδιον, ὁ δὲ δεύτερος αὐτοτελής ἐστι πρὸς τὸ γνωρίζειν τί ποτ᾿\nἐστὶ τὸ λεγόμενον καθ᾿ αὑτό. Προσκείσθωσαν δὲ τῷ συμβεβηκότι καὶ αἱ πρὸς ἄλληλα\nσυγκρίσεις, ὁπωσοῦν ἀπὸ τοῦ συμβεβηκότος λεγόμεναι, οἷον πότερον τὸ καλὸν ἢ\nτὸ συμφέρον αἱρετώτερον, καὶ πότερον ὁ κατ᾿ ἀρετὴν ἢ ὁ κατ᾿ ἀπόλαυσιν ἡδίων βίος,\nκαὶ εἴ τι ἄλλο παραπλησίως τυγχάνει τούτοις λεγόμενον· ἐπὶ πάντων γὰρ τῶν\nτοιούτων, ποτέρῳ μᾶλλον τὸ κατηγορούμενον συμβέβηκεν, ἡ ζήτησις γίνεται. Δῆλον δ᾿\nἐξ αὐτῶν ὅτι τὸ συμβεβηκὸς οὐθὲν κωλύει ποτὲ καὶ πρός τι ἴδιον γίνεσθαι,\nοἷον τὸ καθῆσθαι συμβεβηκὸς ὄν, ὅταν τις μόνος κάθηται, τότε ἴδιον ἔσται, μὴ\nμόνου δὲ καθημένου πρὸς τοὺς μὴ καθημένους ἴδιον. Ὥστε καὶ πρός τι καὶ ποτὲ οὐθὲν\nκωλύει τὸ συμβεβηκὸς ἴδιον γίνεσθαι. Ἁπλῶς δ᾿ ἴδιον οὐκ ἔσται.\n\n',
 '\nΜὴ λανθανέτω δ᾿ ἡμᾶς ὅτι τὰ πρὸς τὸ ἴδιον καὶ τὸ γένος καὶ τὸ συμβεβηκὸς πάντα\nκαὶ πρὸς τοὺς ὁρισμοὺς ἁρμόσει λέγεσθαι. Δείξαντες γὰρ ὅτι οὐ μόνῳ ὑπάρχει τῷ\nὑπὸ τὸν ὁρισμόν, ὥσπερ καὶ ἐπὶ τοῦ ἰδίου, ἢ ὅτι οὐ γένος τὸ ἀποδοθὲν ἐν τῷ\nὁρισμῷ, ἢ ὅτι οὐχ ὑπάρχει τι τῶν ἐν τῷ λόγῳ ῥηθέντων, ὅπερ καὶ ἐπὶ τοῦ\nσυμβεβηκότος ἂν ῥηθείη, ἀνῃρηκότες ἐσόμεθα τὸν ὁρισμόν· ὥστε κατὰ τὸν\nἔμπροσθεν ἀποδοθέντα λόγον ἅπαντ᾿ ἂν εἴη τρόπον τινὰ ὁρικὰ τὰ κατηριθμημένα.\nἈλλ᾿ οὐ διὰ τοῦτο μίαν ἐπὶ πάντων καθόλου μέθοδον ζητητέον· οὔτε γὰρ ῥᾴδιον\nεὑρεῖν τοῦτ᾿ ἐστίν, εἴ θ᾿ εὑρεθείη, παντελῶς ἀσαφὴς καὶ δύσχρηστος ἂν εἴη πρὸς\nτὴν προκειμένην πραγματείαν. Ἰδίας δὲ καθ᾿ ἕκαστον τῶν διορισθέντων γενῶν\nἀποδοθείσης μεθόδου ῥᾷον ἐκ τῶν περὶ ἕκαστον οἰκείων ἡ διέξοδος τοῦ προκειμένου\nγένοιτ᾿ ἄν. Ὥστε τύπῳ μέν, καθάπερ εἴρηται πρότερον, διαιρετέον, τῶν δὲ\nλοιπῶν τὰ μάλισθ᾿ ἑκάστοις οἰκεῖα προσαπτέον, ὁρικά τε καὶ γενικὰ προσαγορεύοντας\nαὐτά. Σχεδὸν δὲ προσῆπται τὰ ῥηθέντα πρὸς ἑκάστοις.\n\n',
 '\nΠρῶτον δὲ πάντων περὶ ταὐτοῦ διοριστέον, ποσαχῶς λέγεται. Δόξειε δ᾿ ἂν τὸ ταὐτὸν\nὡς τύπῳ λαβεῖν τριχῇ διαιρεῖσθαι. Ἀριθμῷ γὰρ ἢ εἴδει ἢ γένει τὸ ταὐτὸν εἰώθαμεν\nπροσαγορεύειν, ἀριθμῷ μὲν ὧν ὀνόματα πλείω τὸ δὲ πρᾶγμα ἕν, οἷον λώπιον καὶ\nἱμάτιον, εἴδει δὲ ὅσα πλείω ὄντα ἀδιάφορα κατὰ τὸ εἶδός ἐστι, καθάπερ ἄνθρωπος\nἀνθρώπῳ καὶ ἵππος ἵππῳ· τὰ γὰρ τοιαῦτα τῷ εἴδει λέγεται ταὐτά, ὅσα ὑπὸ ταὐτὸ\nεἶδος. Ὁμοίως δὲ καὶ γένει ταὐτά, ὅσα ὑπὸ ταὐτὸ γένος ἐστίν, οἷον ἵππος ἀνθρώπῳ.\nΔόξειε δ᾿ ἂν τὸ ἀπὸ τῆς αὐτῆς κρήνης ὕδωρ ταὐτὸν λεγόμενον ἔχειν τινὰ\nδιαφορὰν παρὰ τοὺς εἰρημένους τρόπους· οὐ μὴν ἀλλὰ καὶ τὸ τοιοῦτόν γε ἐν τῷ\nαὐτῷ τετάχθω τοῖς καθ᾿ ἓν εἶδος ὁπωσοῦν λεγομένοις. Ἅπαντα γὰρ τὰ τοιαῦτα συγγενῆ\nκαὶ παραπλήσια ἀλλήλοις ἔοικεν εἶναι. Πᾶν μὲν γὰρ ὕδωρ παντὶ ταὐτὸν τῷ εἴδει\nλέγεται διὰ τὸ ἔχειν τινὰ ὁμοιότητα, τὸ δ᾿ ἀπὸ τῆς αὐτῆς κρήνης ὕδωρ οὐδενὶ ἄλλῳ\nδιαφέρει ἀλλ᾿ ἢ τῷ σφοδροτέραν εἶναι τὴν ὁμοιότητα· διὸ οὐ χωρίζομεν αὐτὸ\nτῶν καθ᾿ ἓν εἶδος ὁπωσοῦν λεγομένων. Μάλιστα δ᾿ ὁμολογουμένως τὸ ἓν\nἀριθμῷ ταὐτὸν παρὰ πᾶσι δοκεῖ λέγεσθαι. Εἴωθε δὲ καὶ τοῦτο ἀποδίδοσθαι πλεοναχῶς,\nκυριώτατα μὲν καὶ πρώτως ὅταν ὀνόματι ἢ ὅρῳ τὸ ταὐτὸν ἀποδοθῇ, καθάπερ\nἱμάτιον λωπίῳ καὶ ζῷον πεζὸν δίπουν ἀνθρώπῳ, δεύτερον δ᾿ ὅταν τῷ ἰδίῳ,\nκαθάπερ τὸ ἐπιστήμης δεκτικὸν ἀνθρώπῳ καὶ τὸ τῇ φύσει ἄνω φερόμενον πυρί, τρίτον\nδ᾿ ὅταν ἀπὸ τοῦ συμβεβηκότος, οἷον τὸ καθήμενον ἢ τὸ μουσικὸν Σωκράτει.\nΠάντα γὰρ ταῦτα τὸ ἓν ἀριθμῷ βούλεται σημαίνειν. Ὅτι δ᾿ ἀληθὲς τὸ νῦν ῥηθέν\nἐστιν, ἐκ τῶν μεταβαλλόντων τὰς προσηγορίας μάλιστ᾿ ἄν τις καταμάθοι. Πολλάκις\nγὰρ ἐπιτάσσοντες ὀνόματι καλέσαι τινὰ τῶν καθημένων μεταβάλλομεν, ὅταν τύχῃ\nμὴ συνιεὶς ᾧ τὴν πρόσταξιν ποιούμεθα, ὡς ἀπὸ τοῦ συμβεβηκότος αὐτοῦ μᾶλλον\nσυνήσοντος, καὶ κελεύομεν τὸν καθήμενον ἢ διαλεγόμενον καλέσαι πρὸς ἡμᾶς,\nδῆλον ὡς ταὐτὸν ὑπολαμβάνοντες κατά τε τοὔνομα καὶ κατὰ τὸ συμβεβηκὸς σημαίνειν.\n\n',
 '\nΤὸ μὲν οὖν ταὐτόν, καθάπερ εἴρηται, τριχῇ διῃρήσθω. ὅτι δ᾿ ἐκ τῶν πρότερον\nεἰρημένων οἱ λόγοι καὶ διὰ τούτων καὶ πρὸς ταῦτα, μία μὲν πίστις ἡ διὰ τῆς\nἐπαγωγῆς· εἰ γάρ τις ἐπισκοποίη ἑκάστην τῶν προτάσεων καὶ τῶν προβλημάτων,\nφαίνοιτ᾿ ἂν ἢ ἀπὸ τοῦ ὅρου ἢ ἀπὸ τοῦ ἰδίου ἢ ἀπὸ τοῦ γένους ἢ ἀπὸ τοῦ\nσυμβεβηκότος γεγενημένη. Ἄλλη δὲ πίστις ἡ διὰ συλλογισμοῦ. Ἀνάγκη γὰρ πᾶν τὸ περί\nτινος κατηγορούμενον ἤτοι ἀντικατηγορεῖσθαι τοῦ πράγματος ἢ μή. Καὶ εἰ μὲν\nἀντικατηγορεῖται, ὅρος ἢ ἴδιον ἂν εἴη· εἰ μὲν γὰρ σημαίνει τὸ τί ἦν εἶναι, ὅρος,\nεἰ δὲ μὴ σημαίνει, ἴδιον· τοῦτο γὰρ ἦν ἴδιον, τὸ ἀντικατηγορούμενον μέν, μὴ\nσημαῖνον δὲ τὸ τί ἦν εἶναι. Εἰ δὲ μὴ ἀντικατηγορεῖται τοῦ πράγματος, ἤτοι\nτῶν ἐν τῷ ὁρισμῷ τοῦ ὑποκειμένου λεγομένων ἐστὶν ἢ οὔ. Καὶ εἰ μὲν τῶν ἐν τῷ\nὁρισμῷ λεγομένων, γένος ἢ διαφορὰ ἂν εἴη, ἐπειδὴ ὁ ὁρισμὸς ἐκ γένους καὶ διαφορῶν\nφορῶν ἐστίν· εἰ δὲ μὴ τῶν ἐν τῷ ὁρισμῷ λεγομένων ἐστί, δῆλον ὅτι\nσυμβεβηκὸς ἂν εἴη· τὸ γὰρ συμβεβηκὸς ἐλέγετο ὃ μήτε ὅρος μήτε γένος μήτε ἴδιόν\nἐστιν, ὑπάρχει δὲ τῷ πράγματι.\n\n',
 '\nΜετὰ τοίνυν ταῦτα δεῖ διορίσασθαι τὰ γένη τῶν κατηγοριῶν, ἐν οἷς ὑπάρχουσιν αἱ\nῥηθεῖσαι τέτταρες. Ἔστι δὲ ταῦτα τὸν ἀριθμὸν δέκα, τί ἐστι, ποσόν, ποιόν, πρός\nτι, ποῦ, ποτέ, κεῖσθαι, ἔχειν, ποιεῖν, πάσχειν. Ἀεὶ γὰρ τὸ συμβεβηκὸς καὶ τὸ\nγένος καὶ τὸ ἴδιον καὶ ὁ ὁρισμὸς ἐν μιᾷ τούτων τῶν κατηγοριῶν ἔσται· πᾶσαι γὰρ ὁ\nὁρισμὸς ἐν μιᾷ τούτων τῶν κατηγοριῶν ἔσται· πᾶσαι γὰρ αἱ διὰ τούτων\nπροτάσεις ἢ τί ἐστιν ἢ ποιὸν ἢ ποσὸν ἢ τῶν ἄλλων τινὰ κατηγοριῶν\nσημαίνουσιν. Δῆλον δ᾿ ἐξ αὐτῶν ὅτι ὁ τὸ τί ἐστι σημαίνων ὁτὲ μὲν οὐσίαν σημαίνει,\nὁτὲ δὲ ποιόν, ὁτὲ δὲ τῶν ἄλλων τινὰ κατηγοριῶν. Ὅταν μὲν γὰρ ἐκκειμένου\nἀνθρώπου φῇ τὸ ἐκκείμενον ἄνθρωπον εἶναι ἢ ζῷον, τί ἐστι λέγει καὶ οὐσίαν\nσημαίνει· ὅταν δὲ χρώματος λευκοῦ ἐκκειμένου φῇ τὸ ἐκκείμενον λευκὸν εἶναι ἢ\nχρῶμα, τί ἐστι λέγει καὶ ποιὸν σημαίνει. Ὁμοίως δὲ καὶ ἐὰν πηχυαίου μεγέθους\nἐκκειμένου φῇ τὸ ἐκκείμενον πηχυαῖον εἶναι μέγεθος, τί ἐστιν ἐρεῖ καὶ ποσὸν\nσημαίνει. Ὁμοίως δὲ καὶ ἐπὶ τῶν ἄλλων· ἕκαστον γὰρ τῶν τοιούτων, ἐάν τε αὐτὸ περὶ\nαὑτοῦ λέγηται ἐάν τε τὸ γένος περὶ τούτου, τί ἐστι σημαίνει. Ὅταν δὲ περὶ\nἑτέρου, οὐ τί ἐστι σημαίνει, ἀλλὰ ποσὸν ἢ ποιὸν ἤ τινα τῶν ἄλλων κατηγοριῶν. Ὥστε\nπερὶ ὧν μὲν οἱ λόγοι καὶ ἐξ ὧν, ταῦτα καὶ τοσαῦτά ἐστι· πῶς δὲ ληψόμεθα καὶ δι᾿\nὧν εὐπορήσομεν, μετὰ ταῦτα λεκτέον.\n\n',
 '\nΠρῶτον τοίνυν διωρίσθω, τί ἐστι πρότασις διαλεκτικὴ καὶ τί πρόβλημα διαλεκτικόν.\nΟὐ γὰρ πᾶσαν πρότασιν οὐδὲ πᾶν πρόβλημα διαλεκτικὸν θετέον· οὐδεὶς γὰρ ἂν\nπροτείνειε νοῦν ἔχων τὸ μηδενὶ δοκοῦν, οὐδὲ προβάλοι τὸ πᾶσι\nφανερὸν ἢ τοῖς πλείστοις· τὰ μὲν γὰρ οὐκ ἔχει ἀπορίαν, τὰ δ᾿ οὐδεὶς ἂν θείη. Ἔστι\nδὲ πρότασις διαλεκτικὴ ἐρώτησις ἔνδοξος ἢ πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς σοφοῖς,\nκαὶ τούτοις ἢ πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς μάλιστα γνωρίμοις, μὴ παράδοξος·\nθείη γὰρ ἄν τις τὸ δοκοῦν τοῖς σοφοῖς, ἐὰν μὴ ἐναντίον ταῖς τῶν πολλῶν\nδόξαις ᾖ. Εἰσὶ δὲ προτάσεις διαλεκτικαὶ καὶ τὰ τοῖς ἐνδόξοις ὅμοια, καὶ τἀναντία\nκατ᾿ ἀντίφασιν τοῖς δοκοῦσιν ἐνδόξοις εἶναι προτεινόμενα, καὶ ὅσαι δόξαι\nκατὰ τέχνας εἰσὶ τὰς εὑρημένας. Εἰ γὰρ ἔνδοξον τὸ τὴν αὐτὴν εἶναι τῶν ἐναντίων\nἐπιστήμην καὶ τὸ αἴσθησιν τὴν αὐτὴν εἶναι τῶν ἐναντίων, ἔνδοξον ἂν φανείη καὶ εἰ\nμίαν ἀριθμῷ γραμματικὴν εἶναι, καὶ αὐλητικὴν μίαν, εἰ δὲ πλείους\nγραμματικάς, καὶ αὐλητικὰς πλείους· πάντα γὰρ ὅμοια καὶ συγγενῆ ταῦτ᾿ ἔοικεν\nεἶναι. Ὁμοίως δὲ καὶ τὰ τοῖς ἐνδόξοις ἐναντία κατ᾿ ἀντίφασιν προτεινόμενα ἔνδοξα\nφανεῖται· εἰ γὰρ ἔνδοξον ὅτι δεῖ τοὺς φίλους εὖ ποιεῖν, καὶ ὅτι οὐ δεῖ κακῶς\nποιεῖν ἔνδοξον. Ἔστι δ᾿ ἐναντίον μὲν ὅτι δεῖ κακῶς ποιεῖν τοὺς φίλους, κατ᾿\nἀντίφασιν δὲ ὅτι οὐ δεῖ κακῶς ποιεῖν. Ὁμοίως δὲ καὶ εἰ δεῖ τοὺς φίλους εὖ ποιεῖν,\nτοὺς ἐχθροὺς οὐ δεῖ. Ἔστι δὲ καὶ τοῦτο κατ᾿ ἀντίφασιν τῶν ἐναντίων· τὸ γὰρ\nἐναντίον ἐστὶν ὅτι δεῖ τοὺς ἐχθροὺς εὖ ποιεῖν. Ὡσαύτως δὲ καὶ ἐπὶ τῶν ἄλλων.\nἜνδοξον δ᾿ ἐν παραβολῇ φανεῖται καὶ τὸ ἐναντίον περὶ τοῦ ἐναντίου, οἷον εἰ\nτοὺς φίλους δεῖ εὖ ποιεῖν, καὶ τοὺς ἐχθροὺς δεῖ κακῶς. Φανείη δ᾿ ἂν καὶ ἐναντίον\nτὸ τοὺς φίλους εὖ ποιεῖν τῷ τοὺς ἐχθροὺς κακῶς· πότερον δὲ καὶ κατ᾿ ἀλήθειαν\nοὕτως ἔχει ἢ οὔ, ἐν τοῖς ὑπὲρ τῶν ἐναντίων λεγομένοις ῥηθήσεται. Δῆλον δ᾿\nὅτι καὶ ὅσαι δόξαι κατὰ τέχνας εἰσί, διαλεκτικαὶ προτάσεις εἰσί· θείη γὰρ ἄν τις\nτὰ δοκοῦντα τοῖς ὑπὲρ τούτων ἐπεσκεμμένοις, οἷον περὶ μὲν τῶν ἐν ἰατρικῇ\nὡς ὁ ἰατρός, περὶ δὲ τῶν ἐν γεωμετρίᾳ ὡς ὁ γεωμέτρης· ὁμοίως δὲ καὶ ἐπὶ τῶν\nἄλλων.\n\n',
 '\nΠρόβλημα δ᾿ ἐστὶ διαλεκτικὸν θεώρημα τὸ συντεῖνον ἢ πρὸς αἵρεσιν καὶ φυγὴν ἢ\nπρὸς ἀλήθειαν καὶ γνῶσιν, ἢ αὐτὸ ἢ ὡς συνεργὸν πρός τι ἕτερον τῶν τοιούτων· περὶ\nοὗ ἢ οὐδετέρως δοξάζουσιν ἢ ἐναντίως οἱ πολλοὶ τοῖς σοφοῖς ἢ οἱ σοφοὶ τοῖς\nπολλοῖς ἢ ἑκατέροι αὐτοὶ ἑαυτοῖς. Ἔνια μὲν γὰρ τῶν προβλημάτων χρήσιμον εἰδέναι\nπρὸς τὸ ἑλέσθαι ἢ φυγεῖν, οἷον πότερον ἡ ἡδονὴ αἱρετὸν ἢ οὔ, ἔνια δὲ πρὸς τὸ\nεἰδέναι μόνον, οἷον πότερον ὁ κόσμος ἀΐδιος ἢ οὔ, ἔνια δὲ αὐτὰ μὲν καθ᾿ αὑτὰ\nπρὸς οὐδέτερον τούτων, συνεργὰ δέ ἐστι πρός τινα τῶν τοιούτων· πολλὰ γὰρ αὐτὰ μὲν\nκαθ᾿ αὑτὰ οὐ βουλόμεθα γνωρίζειν, ἑτέρων δ᾿ ἕνεκα, ὅπως διὰ τούτων ἄλλο τι\nγνωρίσωμεν. Ἔστι δὲ προβλήματα καὶ ὧν ἐναντίοι εἰσὶ συλλογισμοί (ἀπορίαν γὰρ ἔχει\nπότερον οὕτως ἔχει ἢ οὐχ οὕτως διὰ τὸ περὶ ἀμφοτέρων εἶναι λόγους πιθανούς)\nκαὶ περὶ ὧν λόγον μὴ ἔχομεν ὄντων μεγάλων, χαλεπὸν οἰόμενοι εἶναι τὸ διὰ τί\nἀποδοῦναι, οἷον πότερον ὁ κόσμος ἀΐδιος ἢ οὔ· καὶ γὰρ τὰ τοιαῦτα ζητήσειεν ἄν\nτις.\n\nΤὰ μὲν οὖν προβλήματα καὶ αἱ προτάσεις, καθάπερ εἴρηται, διωρίσθω· θέσις δέ\nἐστιν ὑπόληψις παράδοξος τῶν γνωρίμων τινὸς κατὰ φιλοσοφίαν, οἷον ὅτι οὐκ ἔστιν\nἀντιλέγειν, καθάπερ ἔφη Ἀντισθένης, ἢ ὅτι πάντα κινεῖται καθ᾿ Ἡράκλειτον, ἢ\nὅτι ἓν τὸ ὄν, καθάπερ Μέλισσός φησιν· τὸ γὰρ τοῦ τυχόντος ἐναντία ταῖς δόξαις\nἀποφηναμένου φροντίζειν εὔηθες. Ἣ περὶ ὧν λόγον ἔχομεν ἐναντίον ταῖς δόξαις,\nοἷον ὅτι οὐ πᾶν τὸ ὂν ἤτοι γενόμενόν ἐστιν ἢ ἀΐδιον, καθάπερ οἱ σοφισταί\nφασιν· μουσικὸν γὰρ ὄντα γραμματικὸν εἶναι οὔτε γενόμενον οὔτε ἀΐδιον\nὄντα. Τοῦτο γάρ, εἰ καί τινι μὴ δοκεῖ, δόξειεν ἂν διὰ τὸ λόγον ἔχειν.\n\nἜστι μὲν οὖν καὶ ἡ θέσις πρόβλημα· οὐ πᾶν δὲ πρόβλημα θέσις, ἐπειδὴ ἔνια τῶν\nπροβλημάτων τοιαῦτ᾿ ἐστὶ περὶ ὧν οὐδετέρως δοξάζομεν. Ὅτι δέ ἐστι καὶ ἡ θέσις\nπρόβλημα, δῆλον· ἀνάγκη γὰρ ἐκ τῶν εἰρημένων ἢ τοὺς πολλοὺς τοῖς σοφοῖς περὶ\nτὴν θέσιν ἀμφισβητεῖν ἢ ὁποτερουσοῦν ἑαυτοῖς, ἐπειδὴ ὑπόληψίς τις παράδοξος ἡ\nθέσις ἐστίν. Σχεδὸν δὲ νῦν πάντα τὰ διαλεκτικὰ προβλήματα θέσεις καλοῦνται.\nΔιαφερέτω δὲ μηδὲν ὁπωσοῦν λεγόμενον· οὐ γὰρ ὀνοματοποιῆσαι βουλόμενοι\nδιείλομεν οὕτως αὐτά, ἀλλ᾿ ἵνα μὴ λανθάνωσιν ἡμᾶς τίνες αὐτῶν τυγχάνουσιν οὖσαι\nδιαφοραί.\n\nΟὐ δεῖ δὲ πᾶν πρόβλημα οὐδὲ πᾶσαν θέσιν ἐπισκοπεῖν, ἀλλ᾿ ἣν ἀπορήσειεν ἄν τις\nτῶν λόγου δεομένων καὶ μὴ κολάσεως ἢ αἰσθήσεως· οἱ μὲν γὰρ ἀποροῦντες πότερον δεῖ\nτοὺς θεοὺς τιμᾶν καὶ τοὺς γονέας ἀγαπᾶν ἢ οὒ κολάσεως δέονται, οἱ δὲ πότερον\nἡ χιὼν λευκὴ ἢ οὒ αἰσθήσεως. Οὐδὲ δὴ ὧν σύνεγγυς ἡ ἀπόδειξις, οὐδ᾿ ὧν λίαν πόρρω·\nτὰ μὲν γὰρ οὐκ ἔχει ἀπορίαν, τὰ δὲ πλείω ἢ κατὰ γυμναστικήν.\n\n',
 '\nΔιωρισμένων δὲ τούτων χρὴ διελέσθαι πόσα τῶν λόγων εἴδη τῶν διαλεκτικῶν. Ἔστι δὲ\nτὸ μὲν ἐπαγωγή, τὸ δὲ συλλογισμός. Καὶ συλλογισμὸς μὲν τί ἐστιν, εἴρηται\nπρότερον, ἐπαγωγὴ δὲ ἡ ἀπὸ τῶν καθ᾿ ἕκαστον ἐπὶ τὰ καθόλου ἔφοδος, οἷον εἰ\nἔστι κυβερνήτης ὁ ἐπιστάμενος κράτιστος καὶ ἡνίοχος, καὶ ὅλως ἐστὶν ὁ ἐπιστάμενος\nπερὶ ἕκαστον ἄριστος. Ἔστι δ᾿ ἡ μὲν ἐπαγωγὴ πιθανώτερον καὶ σαφέστερον καὶ\nκατὰ τὴν αἴσθησιν γνωριμώτερον καὶ τοῖς πολλοῖς κοινόν, ὁ δὲ συλλογισμὸς\nβιαστικώτερον καὶ πρὸς τοὺς ἀντιλογικοὺς ἐνεργέστερον.\n\n',

In [179]:
import unicodedata

def normalize_greek(text, strip_diacritics=False, normalize_sigma=False):
    """
    Normalize Ancient Greek text.

    Args:
        text (str): Greek text.
        strip_diacritics (bool): Remove accents, breathings, etc.
        normalize_sigma (bool): convert final sigma (ς) to the standard sigma (σ)

    Returns:
        str: Normalized text.
    """
    # Canonical Unicode normalization
    text = unicodedata.normalize("NFC", text)

    # I'll keep capitalization for now.
    # text = text.lower()

    GREEK_RE = re.compile(r"[^Ͱ-Ͽἀ-῿\s]+") 
    text = GREEK_RE.sub("", text)      # Remove non-Greek characters
    text = re.sub(r"\s+", " ", text).strip()

    if strip_diacritics:
        # Decompose characters
        text = unicodedata.normalize("NFD", text)
        # Remove combining marks
        text = "".join(
            c for c in text
            if unicodedata.category(c) != "Mn"
        )
        # Recompose
        text = unicodedata.normalize("NFC", text)

    if normalize_sigma:
        text = text.replace("ς", "σ")

    return text



grc_sections_clean = []
for sec in grc_sections[1:]: 
    grc_sections_clean.append(normalize_greek(sec))

In [181]:
print(len(grc_sections_clean))
display(grc_sections_clean)

83

['ΤΟΠΙΚΩΝ Α Ἡ ΜΕΝ πρόθεσις τῆς πραγματείας μέθοδον εὑρεῖν ἀφ᾿ ἧς δυνησόμεθα συλλογίζεσθαι περὶ παντὸς τοῦ προτεθέντος προβλήματος ἐξ ἐνδόξων καὶ αὐτοὶ λόγον ὑπέχοντες μηθὲν ἐροῦμεν ὑπεναντίον Πρῶτον οὖν ῥητέον τί ἐστι συλλογισμὸς καὶ τίνες αὐτοῦ διαφοραί ὅπως ληφθῇ ὁ διαλεκτικὸς συλλογισμός τοῦτον γὰρ ζητοῦμεν κατὰ τὴν προκειμένην πραγματείαν Ἔστι δὴ συλλογισμὸς λόγος ἐν ᾧ τεθέντων τινῶν ἕτερόν τι τῶν κειμένων ἐξ ἀνάγκης συμβαίνει διὰ τῶν κειμένων Ἀπόδειξις μὲν οὖν ἐστίν ὅταν ἐξ ἀληθῶν καὶ πρώτων ὁ συλλογισμὸς ᾖ ἢ ἐκ τοιούτων ἃ διά τινων πρώτων καὶ ἀληθῶν τῆς περὶ αὐτὰ γνώσεως τὴν ἀρχὴν εἴληφεν διαλεκτικὸς δὲ συλλογισμὸς ὁ ἐξ ἐνδόξων συλλογιζόμενος Ἔστι δὲ ἀληθῆ μὲν καὶ πρῶτα τὰ μὴ δι᾿ ἑτέρων ἀλλὰ δι᾿ αὑτῶν ἔχοντα τὴν πίστιν οὐ δεῖ γὰρ ἐν ταῖς ἐπιστημονικαῖς ἀρχαῖς ἐπιζητεῖσθαι τὸ διὰ τί ἀλλ᾿ ἑκάστην τῶν ἀρχῶν αὐτὴν καθ᾿ ἑαυτὴν εἶναι πιστήν Ἔνδοξα δὲ τὰ δοκοῦντα πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς σοφοῖς καὶ τούτοις ἢ πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς μάλιστα γνωρίμοις καὶ ἐνδόξοις Ἐριστικὸς δ᾿ ἐστὶ συλλογισμὸς ὁ ἐκ φαινομένων ἐνδόξων μὴ ὄντων δέ καὶ ὁ ἐξ ἐνδόξων ἢ φαινομένων ἐνδόξων φαινόμενος Οὐ γὰρ πᾶν τὸ φαινόμενον ἔνδοξον καὶ ἔστιν ἔνδοξον Οὐθὲν γὰρ τῶν λεγομένων ἐνδόξων ἐπιπόλαιον ἔχει παντελῶς τὴν φαντασίαν καθὰ περὶ τὰς τῶν ἐριστικῶν λόγων ἀρχὰς συμβέβηκεν ἔχειν παραχρῆμα γὰρ καὶ ὡς ἐπὶ τὸ πολὺ τοῖς καὶ μικρὰ συνορᾶν δυναμένοις κατάδηλος ἐν αὐτοῖς ἡ τοῦ ψεύδους ἐστὶ φύσις Ὁ μὲν οὖν πρότερος τῶν ῥηθέντων ἐριστικῶν συλλογισμῶν καὶ συλλογισμὸς λεγέσθω ὁ δὲ λοιπὸς ἐριστικὸς μὲν συλλογισμός συλλογισμὸς δ᾿ οὔ ἐπειδὴ φαίνεται μὲν συλλογίζεσθαι συλλογίζεται δ᾿ οὔ Ἔτι δὲ παρὰ τοὺς εἰρημένους ἅπαντας συλλογισμοὺς οἱ ἐκ τῶν περί τινας ἐπιστήμας οἰκείων γινόμενοι παραλογισμοί καθάπερ ἐπὶ τῆς γεωμετρίας καὶ τῶν ταύτῃ συγγενῶν συμβέβηκεν ἔχειν Ἔοικε γὰρ ὁ τρόπος οὗτος διαφέρειν τῶν εἰρημένων συλλογισμῶν οὔτε γὰρ ἐξ ἀληθῶν καὶ πρώτων συλλογίζεται ὁ ψευδογραφῶν οὔτ᾿ ἐξ ἐνδόξων Εἰς γὰρ τὸν ὅρον οὐκ ἐμπίπτει οὔτε γὰρ τὰ πᾶσι δοκοῦντα λαμβάνει οὔτε τὰ τοῖς πλείστοις οὔτε τὰ τοῖς σοφοῖς καὶ τούτοις οὔτε τὰ πᾶσιν οὔτε τοῖς πλείστοις οὔτε τοῖς ἐνδοξοτάτοις ἀλλ᾿ ἐκ τῶν οἰκείων μὲν τῇ ἐπιστήμῃ λημμάτων οὐκ ἀληθῶν δὲ τὸν συλλογισμὸν ποιεῖται Τῷ γὰρ ἢ τὰ ἡμικύκλια περιγράφειν μὴ ὡς δεῖ ἢ γραμμάς τινας ἄγειν μὴ ὡς ἂν ἀχθείησαν τὸν παραλογισμὸν ποιεῖται Εἴδη μὲν οὖν τῶν συλλογισμῶν ὡς τύπῳ περιλαβεῖν ἔστω τὰ εἰρημένα Καθόλου δ᾿ εἰπεῖν περὶ πάντων τῶν εἰρημένων καὶ τῶν μετὰ ταῦτα ῥηθησομένων ἐπὶ τοσοῦτον ἡμῖν διωρίσθω διότι περὶ οὐδενὸς αὐτῶν τὸν ἀκριβῆ λόγον ἀποδοῦναι προαιρούμεθα ἀλλ᾿ ὅσον τύπῳ περὶ αὐτῶν βουλόμεθα διελθεῖν παντελῶς ἱκανὸν ἡγούμενοι κατὰ τὴν προκειμένην μέθοδον τὸ δύνασθαι γνωρίζειν ὁπωσοῦν ἕκαστον αὐτῶν',
 'Ἑπόμενον δ᾿ ἂν εἴη τοῖς εἰρημένοις εἰπεῖν πρὸς πόσα τε καὶ τίνα χρήσιμος ἡ πραγματεία Ἔστι δὴ πρὸς τρία πρὸς γυμνασίαν πρὸς τὰς ἐντεύξεις πρὸς τὰς κατὰ φιλοσοφίαν ἐπιστήμας Ὅτι μὲν οὖν πρὸς γυμνασίαν χρήσιμος ἐξ αὐτῶν καταφανές ἐστι μέθοδον γὰρ ἔχοντες ῥᾷον περὶ τοῦ προτεθέντος ἐπιχειρεῖν δυνησόμεθα Πρὸς δὲ τὰς ἐντεύξεις διότι τὰς τῶν πολλῶν κατηριθμημένοι δόξας οὐκ ἐκ τῶν ἀλλοτρίων ἀλλ᾿ ἐκ τῶν οἰκείων δογμάτων ὁμιλήσομεν πρὸς αὐτούς μεταβιβάζοντες ὅ τι ἂν μὴ καλῶς φαίνωνται λέγειν ἡμῖν Πρὸς δὲ τὰς κατὰ φιλοσοφίαν ἐπιστήμας ὅτι δυνάμενοι πρὸς ἀμφότερα διαπορῆσαι ῥᾷον ἐν ἑκάστοις κατοψόμεθα τἀληθές τε καὶ τὸ ψεῦδος Ἔτι δὲ πρὸς τὰ πρῶτα τῶν περὶ ἑκάστην ἐπιστήμην ἀρχῶν Ἐκ μὲν γὰρ τῶν οἰκείων τῶν κατὰ τὴν προτεθεῖσαν ἐπιστήμην ἀρχῶν ἀδύνατον εἰπεῖν τι περὶ αὐτῶν ἐπειδὴ πρῶται αἱ ἀρχαὶ ἁπάντων εἰσί διὰ δὲ τῶν περὶ ἕκαστα ἐνδόξων ἀνάγκη περὶ αὐτῶν διελθεῖν Τοῦτο δ᾿ ἴδιον ἢ μάλιστα οἰκεῖον τῆς διαλεκτικῆς ἐστίν ἐξεταστικὴ γὰρ οὖσα πρὸς τὰς ἁπασῶν τῶν μεθόδων ἀρχὰς ὁδὸν ἔχει',
 'Ἕξομεν δὲ τελέως τὴν μέθοδον ὅταν ὁμοίως ἔχωμεν ὥσπερ ἐπὶ ῥητορικῆς καὶ ἰατρικῆς καὶ τῶν τοιούτων δυνάμεων Τοῦτο δ᾿ ἐστὶ τὸ ἐκ τῶν ἐνδεχομένων ποιεῖν ἃ προαιρούμεθα Οὔτε γὰρ ὁ ῥητορικὸς ἐκ παντὸς τρόπου πείσει οὔθ᾿ ὁ ἰατρικὸς ὑγιάσει ἀλλ᾿ ἐὰν τῶν ἐνδεχομένων μηδὲν παραλείπῃ ἱκανῶς αὐτὸν ἔχειν τὴν ἐπιστήμην φήσομεν',
 'Πρῶτον οὖν θεωρητέον ἐκ τίνων ἡ μέθοδος Εἰ δὴ λάβοιμεν πρὸς πόσα καὶ ποῖα καὶ ἐκ τίνων οἱ λόγοι καὶ πῶς τούτων εὐπορήσομεν ἔχοιμεν ἂν ἱκανῶς τὸ προκείμενον Ἔστι δ᾿ ἀριθμῷ ἴσα καὶ ταὐτά ἐξ ὧν τε οἱ λόγοι καὶ περὶ ὧν οἱ συλλογισμοί Γίνονται μὲν γὰρ οἱ λόγοι ἐκ τῶν προτάσεων περὶ ὧν δὲ οἱ συλλογισμοί τὰ προβλήματά ἐστι Πᾶσα δὲ πρότασις καὶ πᾶν πρόβλημα ἢ γένος ἢ ἴδιον ἢ συμβεβηκὸς δηλοῖ καὶ γὰρ τὴν διαφορὰν ὡς οὖσαν γενικὴν ὁμοῦ τῷ γένει τακτέον Ἐπεὶ δὲ τοῦ ἰδίου τὸ μὲν τὸ τί ἦν εἶναι σημαίνει τὸ δ᾿ οὐ σημαίνει διῃρήσθω τὸ ἴδιον εἰς ἄμφω τὰ προειρημένα μέρη καὶ καλείσθω τὸ μὲν τὸ τί ἦν εἶναι σημαῖνον ὅρος τὸ δὲ λοιπὸν κατὰ τὴν κοινὴν περὶ αὐτῶν ἀποδοθεῖσαν ὀνομασίαν προσαγορευέσθω ἴδιον Δῆλον οὖν ἐκ τῶν εἰρημένων ὅτι κατὰ τὴν νῦν διαίρεσιν τέτταρα τὰ πάντα συμβαίνει γίνεσθαι ἢ ἴδιον ἢ ὅρον ἢ γένος ἢ συμβεβηκός Μηδεὶς δ᾿ ἡμᾶς ὑπολάβῃ λέγειν ὡς ἕκαστον τούτων καθ᾿ αὑτὸ λεγόμενον πρότασις ἢ πρόβλημά ἐστιν ἀλλ᾿ ὅτι ἀπὸ τούτων καὶ τὰ προβλήματα καὶ αἱ προτάσεις γίνονται Διαφέρει δὲ τὸ πρόβλημα καὶ ἡ πρότασις τῷ τρόπῳ Οὕτω μὲν γὰρ ῥηθέντος ἆρά γε τὸ ζῷον πεζὸν δίπουν ὁρισμός ἐστιν ἀνθρώπου καὶ ἆρά γε τὸ ζῷον γένος ἐστὶ τοῦ ἀνθρώπου πρότασις γίνεται Ἐὰν δέ πότερον τὸ ζῷον πεζὸν δίπουν ὁρισμός ἐστιν ἀνθρώπου ἢ οὔ καὶ πότερον τὸ ζῷον γένος ἐστίν πρόβλημα γίνεται Ὁμοίως δὲ καὶ ἐπὶ τῶν ἄλλων Ὅστ᾿ εἰκότως ἴσα τῷ ἀριθμῷ τὰ προβλήματα καὶ αἱ προτάσεις εἰσίν Ἀπὸ πάσης γὰρ προτάσεως πρόβλημα ποιήσεις μεταβάλλων τῷ τρόπῳ',
 'Λεκτέον δὲ τί ὅρος τί ἴδιον τί γένος τί συμβεβηκός Ἔστι δ᾿ ὅρος μὲν λόγος ὁ τὸ τί ἦν εἶναι σημαίνων Ἀποδίδοται δὲ ἢ λόγος ἀντ᾿ ὀνόματος ἢ λόγος ἀντὶ λόγου δυνατὸν γὰρ καὶ τῶν ὑπὸ λόγου τινὰ σημαινομένων ὁρίσασθαι Ὅσοι δ᾿ ὁπωσοῦν ὀνόματι τὴν ἀπόδοσιν ποιοῦνται δῆλον ὡς οὐκ ἀποδιδόασιν οὗτοι τὸν τοῦ πράγματος ὁρισμόν ἐπειδὴ πᾶς ὁρισμὸς λόγος τίς ἐστιν Ὁρικὸν μέντοι καὶ τὸ τοιοῦτον θετέον οἷον ὅτι καλόν ἐστι τὸ πρέπον Ὁμοίως δὲ καὶ τὸ πότερον ταὐτὸν αἴσθησις καὶ ἐπιστήμη ἢ ἕτερον καὶ γὰρ περὶ τοὺς ὁρισμούς πότερον ταὐτὸν ἢ ἕτερον ἡ πλείστη γίνεται διατριβή Ἁπλῶς δὲ ὁρικὰ πάντα λεγέσθω τὰ ὑπὸ τὴν αὐτὴν ὄντα μέθοδον τοῖς ὁρισμοῖς Ὅτι δὲ πάντα τὰ νῦν ῥηθέντα τοιαῦτ᾿ ἐστί δῆλον ἐξ αὐτῶν Δυνάμενοι γὰρ ὅτι ταὐτὸν καὶ ὅτι ἕτερον διαλέγεσθαι τῷ αὐτῷ τρόπῳ καὶ πρὸς τοὺς ὁρισμοὺς ἐπιχειρεῖν εὐπορήσομεν δείξαντες γὰρ ὅτι οὐ ταὐτόν ἐστιν ἀνῃρηκότες ἐσόμεθα τὸν ὁρισμόν Οὐ μὴν ἀντιστρέφει γε τὸ νῦν ῥηθέν οὐ γὰρ ἱκανὸν πρὸς τὸ κατασκευάσαι τὸν ὁρισμὸν τὸ δεῖξαι ταὐτὸν ὄν Πρὸς μέντοι τὸ ἀνασκευάσαι αὔταρκες τὸ δεῖξαι ὅτι οὐ ταὐτόν Ἴδιον δ᾿ ἐστὶν ὃ μὴ δηλοῖ μὲν τὸ τί ἦν εἶναι μόνῳ δ᾿ ὑπάρχει καὶ ἀντικατηγορεῖται τοῦ πράγματος οἷον ἴδιον ἀνθρώπου τὸ γραμματικῆς εἶναι δεκτικόν εἰ γὰρ ἄνθρωπός ἐστι γραμματικῆς δεκτικός ἐστι καὶ εἰ γραμματικῆς δεκτικός ἐστιν ἄνθρωπός ἐστιν Οὐθεὶς γὰρ ἴδιον λέγει τὸ ἐνδεχόμενον ἄλλῳ ὑπάρχειν οἷον τὸ καθεύδειν ἀνθρώπῳ οὐδ᾿ ἂν τύχῃ κατά τινα χρόνον μόνῳ ὑπάρχον Εἰ δ᾿ ἄρα τι καὶ λέγοιτο τῶν τοιούτων ἴδιον οὐχ ἁπλῶς ἀλλὰ ποτὲ ἢ πρός τι ἴδιον ῥηθήσεται τὸ μὲν γὰρ ἐκ δεξιῶν εἶναι ποτὲ ἴδιόν ἐστι τὸ δὲ δίπουν πρός τι ἴδιον τυγχάνει λεγόμενον οἷον τῷ ἀνθρώπῳ πρὸς ἵππον καὶ κύνα Ὅτι δὲ τῶν ἐνδεχομένων ἄλλῳ ὑπάρχειν οὐθὲν ἀντικατηγορεῖται δῆλον οὐ γὰρ ἀναγκαῖον εἴ τι καθεύδει ἄνθρωπον εἶναι Γένος δ᾿ ἐστὶ τὸ κατὰ πλειόνων καὶ διαφερόντων τῷ εἴδει ἐν τῷ τί ἐστι κατηγορούμενον Ἐν τῷ τί ἐστι δὲ κατηγορεῖσθαι τὰ τοιαῦτα λεγέσθω ὅσα ἁρμόττει ἀποδοῦναι ἐρωτηθέντας τί ἐστι τὸ προκείμενον καθάπερ ἐπὶ τοῦ ἀνθρώπου ἁρμόττει ἐρωτηθέντα τί ἐστι τὸ προκείμενον εἰπεῖν ὅτι ζῷον Γενικὸν δὲ καὶ τὸ πότερον ἐν τῷ αὐτῷ γένει ἄλλο ἄλλῳ ἢ ἐν ἑτέρῳ Καὶ γὰρ τὸ τοιοῦτον ὑπὸ τὴν αὐτὴν μέθοδον πίπτει τῷ γένει διαλεχθέντες γὰρ ὅτι τὸ ζῷον γένος τοῦ ἀνθρώπου ὁμοίως δὲ καὶ τοῦ βοός διειλεγμένοι ἐσόμεθα ὅτι ἐν τῷ αὐτῷ γένει Ἐὰν δὲ τοῦ μὲν ἑτέρου δείξωμεν ὅτι γένος ἐστί τοῦ δὲ ἑτέρου ὅτι οὐκ ἔστι διειλεγμένοι ἐσόμεθα ὅτι οὐκ ἐν τῷ αὐτῷ γένει ταῦτ᾿ ἐστίν Συμβεβηκὸς δέ ἐστιν ὃ μηδὲν μὲν τούτων ἐστί μήτε ὅρος μήτε ἴδιον μήτε γένος ὑπάρχει δὲ τῷ πράγματι καὶ ὃ ἐνδέχεται ὑπάρχειν ὁτῳοῦν ἑνὶ καὶ τῷ αὐτῷ καὶ μὴ ὑπάρχειν οἷον τὸ καθῆσθαι ἐνδέχεται ὑπάρχειν τινὶ τῷ αὐτῷ καὶ μὴ ὑπάρχειν Ὁμοίως δὲ καὶ τὸ λευκόν τὸ γὰρ αὐτὸ οὐθὲν κωλύει ὁτὲ μὲν λευκὸν ὁτὲ δὲ μὴ λευκὸν εἶναι Ἔστι δὲ τῶν τοῦ συμβεβηκότος ὁρισμῶν ὁ δεύτερος βελτίων τοῦ μὲν γὰρ πρώτου ῥηθέντος ἀναγκαῖον εἰ μέλλει τις συνήσειν προειδέναι τί ἐστιν ὅρος καὶ γένος καὶ ἴδιον ὁ δὲ δεύτερος αὐτοτελής ἐστι πρὸς τὸ γνωρίζειν τί ποτ᾿ ἐστὶ τὸ λεγόμενον καθ᾿ αὑτό Προσκείσθωσαν δὲ τῷ συμβεβηκότι καὶ αἱ πρὸς ἄλληλα συγκρίσεις ὁπωσοῦν ἀπὸ τοῦ συμβεβηκότος λεγόμεναι οἷον πότερον τὸ καλὸν ἢ τὸ συμφέρον αἱρετώτερον καὶ πότερον ὁ κατ᾿ ἀρετὴν ἢ ὁ κατ᾿ ἀπόλαυσιν ἡδίων βίος καὶ εἴ τι ἄλλο παραπλησίως τυγχάνει τούτοις λεγόμενον ἐπὶ πάντων γὰρ τῶν τοιούτων ποτέρῳ μᾶλλον τὸ κατηγορούμενον συμβέβηκεν ἡ ζήτησις γίνεται Δῆλον δ᾿ ἐξ αὐτῶν ὅτι τὸ συμβεβηκὸς οὐθὲν κωλύει ποτὲ καὶ πρός τι ἴδιον γίνεσθαι οἷον τὸ καθῆσθαι συμβεβηκὸς ὄν ὅταν τις μόνος κάθηται τότε ἴδιον ἔσται μὴ μόνου δὲ καθημένου πρὸς τοὺς μὴ καθημένους ἴδιον Ὥστε καὶ πρός τι καὶ ποτὲ οὐθὲν κωλύει τὸ συμβεβηκὸς ἴδιον γίνεσθαι Ἁπλῶς δ᾿ ἴδιον οὐκ ἔσται',
 'Μὴ λανθανέτω δ᾿ ἡμᾶς ὅτι τὰ πρὸς τὸ ἴδιον καὶ τὸ γένος καὶ τὸ συμβεβηκὸς πάντα καὶ πρὸς τοὺς ὁρισμοὺς ἁρμόσει λέγεσθαι Δείξαντες γὰρ ὅτι οὐ μόνῳ ὑπάρχει τῷ ὑπὸ τὸν ὁρισμόν ὥσπερ καὶ ἐπὶ τοῦ ἰδίου ἢ ὅτι οὐ γένος τὸ ἀποδοθὲν ἐν τῷ ὁρισμῷ ἢ ὅτι οὐχ ὑπάρχει τι τῶν ἐν τῷ λόγῳ ῥηθέντων ὅπερ καὶ ἐπὶ τοῦ συμβεβηκότος ἂν ῥηθείη ἀνῃρηκότες ἐσόμεθα τὸν ὁρισμόν ὥστε κατὰ τὸν ἔμπροσθεν ἀποδοθέντα λόγον ἅπαντ᾿ ἂν εἴη τρόπον τινὰ ὁρικὰ τὰ κατηριθμημένα Ἀλλ᾿ οὐ διὰ τοῦτο μίαν ἐπὶ πάντων καθόλου μέθοδον ζητητέον οὔτε γὰρ ῥᾴδιον εὑρεῖν τοῦτ᾿ ἐστίν εἴ θ᾿ εὑρεθείη παντελῶς ἀσαφὴς καὶ δύσχρηστος ἂν εἴη πρὸς τὴν προκειμένην πραγματείαν Ἰδίας δὲ καθ᾿ ἕκαστον τῶν διορισθέντων γενῶν ἀποδοθείσης μεθόδου ῥᾷον ἐκ τῶν περὶ ἕκαστον οἰκείων ἡ διέξοδος τοῦ προκειμένου γένοιτ᾿ ἄν Ὥστε τύπῳ μέν καθάπερ εἴρηται πρότερον διαιρετέον τῶν δὲ λοιπῶν τὰ μάλισθ᾿ ἑκάστοις οἰκεῖα προσαπτέον ὁρικά τε καὶ γενικὰ προσαγορεύοντας αὐτά Σχεδὸν δὲ προσῆπται τὰ ῥηθέντα πρὸς ἑκάστοις',
 'Πρῶτον δὲ πάντων περὶ ταὐτοῦ διοριστέον ποσαχῶς λέγεται Δόξειε δ᾿ ἂν τὸ ταὐτὸν ὡς τύπῳ λαβεῖν τριχῇ διαιρεῖσθαι Ἀριθμῷ γὰρ ἢ εἴδει ἢ γένει τὸ ταὐτὸν εἰώθαμεν προσαγορεύειν ἀριθμῷ μὲν ὧν ὀνόματα πλείω τὸ δὲ πρᾶγμα ἕν οἷον λώπιον καὶ ἱμάτιον εἴδει δὲ ὅσα πλείω ὄντα ἀδιάφορα κατὰ τὸ εἶδός ἐστι καθάπερ ἄνθρωπος ἀνθρώπῳ καὶ ἵππος ἵππῳ τὰ γὰρ τοιαῦτα τῷ εἴδει λέγεται ταὐτά ὅσα ὑπὸ ταὐτὸ εἶδος Ὁμοίως δὲ καὶ γένει ταὐτά ὅσα ὑπὸ ταὐτὸ γένος ἐστίν οἷον ἵππος ἀνθρώπῳ Δόξειε δ᾿ ἂν τὸ ἀπὸ τῆς αὐτῆς κρήνης ὕδωρ ταὐτὸν λεγόμενον ἔχειν τινὰ διαφορὰν παρὰ τοὺς εἰρημένους τρόπους οὐ μὴν ἀλλὰ καὶ τὸ τοιοῦτόν γε ἐν τῷ αὐτῷ τετάχθω τοῖς καθ᾿ ἓν εἶδος ὁπωσοῦν λεγομένοις Ἅπαντα γὰρ τὰ τοιαῦτα συγγενῆ καὶ παραπλήσια ἀλλήλοις ἔοικεν εἶναι Πᾶν μὲν γὰρ ὕδωρ παντὶ ταὐτὸν τῷ εἴδει λέγεται διὰ τὸ ἔχειν τινὰ ὁμοιότητα τὸ δ᾿ ἀπὸ τῆς αὐτῆς κρήνης ὕδωρ οὐδενὶ ἄλλῳ διαφέρει ἀλλ᾿ ἢ τῷ σφοδροτέραν εἶναι τὴν ὁμοιότητα διὸ οὐ χωρίζομεν αὐτὸ τῶν καθ᾿ ἓν εἶδος ὁπωσοῦν λεγομένων Μάλιστα δ᾿ ὁμολογουμένως τὸ ἓν ἀριθμῷ ταὐτὸν παρὰ πᾶσι δοκεῖ λέγεσθαι Εἴωθε δὲ καὶ τοῦτο ἀποδίδοσθαι πλεοναχῶς κυριώτατα μὲν καὶ πρώτως ὅταν ὀνόματι ἢ ὅρῳ τὸ ταὐτὸν ἀποδοθῇ καθάπερ ἱμάτιον λωπίῳ καὶ ζῷον πεζὸν δίπουν ἀνθρώπῳ δεύτερον δ᾿ ὅταν τῷ ἰδίῳ καθάπερ τὸ ἐπιστήμης δεκτικὸν ἀνθρώπῳ καὶ τὸ τῇ φύσει ἄνω φερόμενον πυρί τρίτον δ᾿ ὅταν ἀπὸ τοῦ συμβεβηκότος οἷον τὸ καθήμενον ἢ τὸ μουσικὸν Σωκράτει Πάντα γὰρ ταῦτα τὸ ἓν ἀριθμῷ βούλεται σημαίνειν Ὅτι δ᾿ ἀληθὲς τὸ νῦν ῥηθέν ἐστιν ἐκ τῶν μεταβαλλόντων τὰς προσηγορίας μάλιστ᾿ ἄν τις καταμάθοι Πολλάκις γὰρ ἐπιτάσσοντες ὀνόματι καλέσαι τινὰ τῶν καθημένων μεταβάλλομεν ὅταν τύχῃ μὴ συνιεὶς ᾧ τὴν πρόσταξιν ποιούμεθα ὡς ἀπὸ τοῦ συμβεβηκότος αὐτοῦ μᾶλλον συνήσοντος καὶ κελεύομεν τὸν καθήμενον ἢ διαλεγόμενον καλέσαι πρὸς ἡμᾶς δῆλον ὡς ταὐτὸν ὑπολαμβάνοντες κατά τε τοὔνομα καὶ κατὰ τὸ συμβεβηκὸς σημαίνειν',
 'Τὸ μὲν οὖν ταὐτόν καθάπερ εἴρηται τριχῇ διῃρήσθω ὅτι δ᾿ ἐκ τῶν πρότερον εἰρημένων οἱ λόγοι καὶ διὰ τούτων καὶ πρὸς ταῦτα μία μὲν πίστις ἡ διὰ τῆς ἐπαγωγῆς εἰ γάρ τις ἐπισκοποίη ἑκάστην τῶν προτάσεων καὶ τῶν προβλημάτων φαίνοιτ᾿ ἂν ἢ ἀπὸ τοῦ ὅρου ἢ ἀπὸ τοῦ ἰδίου ἢ ἀπὸ τοῦ γένους ἢ ἀπὸ τοῦ συμβεβηκότος γεγενημένη Ἄλλη δὲ πίστις ἡ διὰ συλλογισμοῦ Ἀνάγκη γὰρ πᾶν τὸ περί τινος κατηγορούμενον ἤτοι ἀντικατηγορεῖσθαι τοῦ πράγματος ἢ μή Καὶ εἰ μὲν ἀντικατηγορεῖται ὅρος ἢ ἴδιον ἂν εἴη εἰ μὲν γὰρ σημαίνει τὸ τί ἦν εἶναι ὅρος εἰ δὲ μὴ σημαίνει ἴδιον τοῦτο γὰρ ἦν ἴδιον τὸ ἀντικατηγορούμενον μέν μὴ σημαῖνον δὲ τὸ τί ἦν εἶναι Εἰ δὲ μὴ ἀντικατηγορεῖται τοῦ πράγματος ἤτοι τῶν ἐν τῷ ὁρισμῷ τοῦ ὑποκειμένου λεγομένων ἐστὶν ἢ οὔ Καὶ εἰ μὲν τῶν ἐν τῷ ὁρισμῷ λεγομένων γένος ἢ διαφορὰ ἂν εἴη ἐπειδὴ ὁ ὁρισμὸς ἐκ γένους καὶ διαφορῶν φορῶν ἐστίν εἰ δὲ μὴ τῶν ἐν τῷ ὁρισμῷ λεγομένων ἐστί δῆλον ὅτι συμβεβηκὸς ἂν εἴη τὸ γὰρ συμβεβηκὸς ἐλέγετο ὃ μήτε ὅρος μήτε γένος μήτε ἴδιόν ἐστιν ὑπάρχει δὲ τῷ πράγματι',
 'Μετὰ τοίνυν ταῦτα δεῖ διορίσασθαι τὰ γένη τῶν κατηγοριῶν ἐν οἷς ὑπάρχουσιν αἱ ῥηθεῖσαι τέτταρες Ἔστι δὲ ταῦτα τὸν ἀριθμὸν δέκα τί ἐστι ποσόν ποιόν πρός τι ποῦ ποτέ κεῖσθαι ἔχειν ποιεῖν πάσχειν Ἀεὶ γὰρ τὸ συμβεβηκὸς καὶ τὸ γένος καὶ τὸ ἴδιον καὶ ὁ ὁρισμὸς ἐν μιᾷ τούτων τῶν κατηγοριῶν ἔσται πᾶσαι γὰρ ὁ ὁρισμὸς ἐν μιᾷ τούτων τῶν κατηγοριῶν ἔσται πᾶσαι γὰρ αἱ διὰ τούτων προτάσεις ἢ τί ἐστιν ἢ ποιὸν ἢ ποσὸν ἢ τῶν ἄλλων τινὰ κατηγοριῶν σημαίνουσιν Δῆλον δ᾿ ἐξ αὐτῶν ὅτι ὁ τὸ τί ἐστι σημαίνων ὁτὲ μὲν οὐσίαν σημαίνει ὁτὲ δὲ ποιόν ὁτὲ δὲ τῶν ἄλλων τινὰ κατηγοριῶν Ὅταν μὲν γὰρ ἐκκειμένου ἀνθρώπου φῇ τὸ ἐκκείμενον ἄνθρωπον εἶναι ἢ ζῷον τί ἐστι λέγει καὶ οὐσίαν σημαίνει ὅταν δὲ χρώματος λευκοῦ ἐκκειμένου φῇ τὸ ἐκκείμενον λευκὸν εἶναι ἢ χρῶμα τί ἐστι λέγει καὶ ποιὸν σημαίνει Ὁμοίως δὲ καὶ ἐὰν πηχυαίου μεγέθους ἐκκειμένου φῇ τὸ ἐκκείμενον πηχυαῖον εἶναι μέγεθος τί ἐστιν ἐρεῖ καὶ ποσὸν σημαίνει Ὁμοίως δὲ καὶ ἐπὶ τῶν ἄλλων ἕκαστον γὰρ τῶν τοιούτων ἐάν τε αὐτὸ περὶ αὑτοῦ λέγηται ἐάν τε τὸ γένος περὶ τούτου τί ἐστι σημαίνει Ὅταν δὲ περὶ ἑτέρου οὐ τί ἐστι σημαίνει ἀλλὰ ποσὸν ἢ ποιὸν ἤ τινα τῶν ἄλλων κατηγοριῶν Ὥστε περὶ ὧν μὲν οἱ λόγοι καὶ ἐξ ὧν ταῦτα καὶ τοσαῦτά ἐστι πῶς δὲ ληψόμεθα καὶ δι᾿ ὧν εὐπορήσομεν μετὰ ταῦτα λεκτέον',
 'Πρῶτον τοίνυν διωρίσθω τί ἐστι πρότασις διαλεκτικὴ καὶ τί πρόβλημα διαλεκτικόν Οὐ γὰρ πᾶσαν πρότασιν οὐδὲ πᾶν πρόβλημα διαλεκτικὸν θετέον οὐδεὶς γὰρ ἂν προτείνειε νοῦν ἔχων τὸ μηδενὶ δοκοῦν οὐδὲ προβάλοι τὸ πᾶσι φανερὸν ἢ τοῖς πλείστοις τὰ μὲν γὰρ οὐκ ἔχει ἀπορίαν τὰ δ᾿ οὐδεὶς ἂν θείη Ἔστι δὲ πρότασις διαλεκτικὴ ἐρώτησις ἔνδοξος ἢ πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς σοφοῖς καὶ τούτοις ἢ πᾶσιν ἢ τοῖς πλείστοις ἢ τοῖς μάλιστα γνωρίμοις μὴ παράδοξος θείη γὰρ ἄν τις τὸ δοκοῦν τοῖς σοφοῖς ἐὰν μὴ ἐναντίον ταῖς τῶν πολλῶν δόξαις ᾖ Εἰσὶ δὲ προτάσεις διαλεκτικαὶ καὶ τὰ τοῖς ἐνδόξοις ὅμοια καὶ τἀναντία κατ᾿ ἀντίφασιν τοῖς δοκοῦσιν ἐνδόξοις εἶναι προτεινόμενα καὶ ὅσαι δόξαι κατὰ τέχνας εἰσὶ τὰς εὑρημένας Εἰ γὰρ ἔνδοξον τὸ τὴν αὐτὴν εἶναι τῶν ἐναντίων ἐπιστήμην καὶ τὸ αἴσθησιν τὴν αὐτὴν εἶναι τῶν ἐναντίων ἔνδοξον ἂν φανείη καὶ εἰ μίαν ἀριθμῷ γραμματικὴν εἶναι καὶ αὐλητικὴν μίαν εἰ δὲ πλείους γραμματικάς καὶ αὐλητικὰς πλείους πάντα γὰρ ὅμοια καὶ συγγενῆ ταῦτ᾿ ἔοικεν εἶναι Ὁμοίως δὲ καὶ τὰ τοῖς ἐνδόξοις ἐναντία κατ᾿ ἀντίφασιν προτεινόμενα ἔνδοξα φανεῖται εἰ γὰρ ἔνδοξον ὅτι δεῖ τοὺς φίλους εὖ ποιεῖν καὶ ὅτι οὐ δεῖ κακῶς ποιεῖν ἔνδοξον Ἔστι δ᾿ ἐναντίον μὲν ὅτι δεῖ κακῶς ποιεῖν τοὺς φίλους κατ᾿ ἀντίφασιν δὲ ὅτι οὐ δεῖ κακῶς ποιεῖν Ὁμοίως δὲ καὶ εἰ δεῖ τοὺς φίλους εὖ ποιεῖν τοὺς ἐχθροὺς οὐ δεῖ Ἔστι δὲ καὶ τοῦτο κατ᾿ ἀντίφασιν τῶν ἐναντίων τὸ γὰρ ἐναντίον ἐστὶν ὅτι δεῖ τοὺς ἐχθροὺς εὖ ποιεῖν Ὡσαύτως δὲ καὶ ἐπὶ τῶν ἄλλων Ἔνδοξον δ᾿ ἐν παραβολῇ φανεῖται καὶ τὸ ἐναντίον περὶ τοῦ ἐναντίου οἷον εἰ τοὺς φίλους δεῖ εὖ ποιεῖν καὶ τοὺς ἐχθροὺς δεῖ κακῶς Φανείη δ᾿ ἂν καὶ ἐναντίον τὸ τοὺς φίλους εὖ ποιεῖν τῷ τοὺς ἐχθροὺς κακῶς πότερον δὲ καὶ κατ᾿ ἀλήθειαν οὕτως ἔχει ἢ οὔ ἐν τοῖς ὑπὲρ τῶν ἐναντίων λεγομένοις ῥηθήσεται Δῆλον δ᾿ ὅτι καὶ ὅσαι δόξαι κατὰ τέχνας εἰσί διαλεκτικαὶ προτάσεις εἰσί θείη γὰρ ἄν τις τὰ δοκοῦντα τοῖς ὑπὲρ τούτων ἐπεσκεμμένοις οἷον περὶ μὲν τῶν ἐν ἰατρικῇ ὡς ὁ ἰατρός περὶ δὲ τῶν ἐν γεωμετρίᾳ ὡς ὁ γεωμέτρης ὁμοίως δὲ καὶ ἐπὶ τῶν ἄλλων',
 'Πρόβλημα δ᾿ ἐστὶ διαλεκτικὸν θεώρημα τὸ συντεῖνον ἢ πρὸς αἵρεσιν καὶ φυγὴν ἢ πρὸς ἀλήθειαν καὶ γνῶσιν ἢ αὐτὸ ἢ ὡς συνεργὸν πρός τι ἕτερον τῶν τοιούτων περὶ οὗ ἢ οὐδετέρως δοξάζουσιν ἢ ἐναντίως οἱ πολλοὶ τοῖς σοφοῖς ἢ οἱ σοφοὶ τοῖς πολλοῖς ἢ ἑκατέροι αὐτοὶ ἑαυτοῖς Ἔνια μὲν γὰρ τῶν προβλημάτων χρήσιμον εἰδέναι πρὸς τὸ ἑλέσθαι ἢ φυγεῖν οἷον πότερον ἡ ἡδονὴ αἱρετὸν ἢ οὔ ἔνια δὲ πρὸς τὸ εἰδέναι μόνον οἷον πότερον ὁ κόσμος ἀΐδιος ἢ οὔ ἔνια δὲ αὐτὰ μὲν καθ᾿ αὑτὰ πρὸς οὐδέτερον τούτων συνεργὰ δέ ἐστι πρός τινα τῶν τοιούτων πολλὰ γὰρ αὐτὰ μὲν καθ᾿ αὑτὰ οὐ βουλόμεθα γνωρίζειν ἑτέρων δ᾿ ἕνεκα ὅπως διὰ τούτων ἄλλο τι γνωρίσωμεν Ἔστι δὲ προβλήματα καὶ ὧν ἐναντίοι εἰσὶ συλλογισμοί ἀπορίαν γὰρ ἔχει πότερον οὕτως ἔχει ἢ οὐχ οὕτως διὰ τὸ περὶ ἀμφοτέρων εἶναι λόγους πιθανούς καὶ περὶ ὧν λόγον μὴ ἔχομεν ὄντων μεγάλων χαλεπὸν οἰόμενοι εἶναι τὸ διὰ τί ἀποδοῦναι οἷον πότερον ὁ κόσμος ἀΐδιος ἢ οὔ καὶ γὰρ τὰ τοιαῦτα ζητήσειεν ἄν τις Τὰ μὲν οὖν προβλήματα καὶ αἱ προτάσεις καθάπερ εἴρηται διωρίσθω θέσις δέ ἐστιν ὑπόληψις παράδοξος τῶν γνωρίμων τινὸς κατὰ φιλοσοφίαν οἷον ὅτι οὐκ ἔστιν ἀντιλέγειν καθάπερ ἔφη Ἀντισθένης ἢ ὅτι πάντα κινεῖται καθ᾿ Ἡράκλειτον ἢ ὅτι ἓν τὸ ὄν καθάπερ Μέλισσός φησιν τὸ γὰρ τοῦ τυχόντος ἐναντία ταῖς δόξαις ἀποφηναμένου φροντίζειν εὔηθες Ἣ περὶ ὧν λόγον ἔχομεν ἐναντίον ταῖς δόξαις οἷον ὅτι οὐ πᾶν τὸ ὂν ἤτοι γενόμενόν ἐστιν ἢ ἀΐδιον καθάπερ οἱ σοφισταί φασιν μουσικὸν γὰρ ὄντα γραμματικὸν εἶναι οὔτε γενόμενον οὔτε ἀΐδιον ὄντα Τοῦτο γάρ εἰ καί τινι μὴ δοκεῖ δόξειεν ἂν διὰ τὸ λόγον ἔχειν Ἔστι μὲν οὖν καὶ ἡ θέσις πρόβλημα οὐ πᾶν δὲ πρόβλημα θέσις ἐπειδὴ ἔνια τῶν προβλημάτων τοιαῦτ᾿ ἐστὶ περὶ ὧν οὐδετέρως δοξάζομεν Ὅτι δέ ἐστι καὶ ἡ θέσις πρόβλημα δῆλον ἀνάγκη γὰρ ἐκ τῶν εἰρημένων ἢ τοὺς πολλοὺς τοῖς σοφοῖς περὶ τὴν θέσιν ἀμφισβητεῖν ἢ ὁποτερουσοῦν ἑαυτοῖς ἐπειδὴ ὑπόληψίς τις παράδοξος ἡ θέσις ἐστίν Σχεδὸν δὲ νῦν πάντα τὰ διαλεκτικὰ προβλήματα θέσεις καλοῦνται Διαφερέτω δὲ μηδὲν ὁπωσοῦν λεγόμενον οὐ γὰρ ὀνοματοποιῆσαι βουλόμενοι διείλομεν οὕτως αὐτά ἀλλ᾿ ἵνα μὴ λανθάνωσιν ἡμᾶς τίνες αὐτῶν τυγχάνουσιν οὖσαι διαφοραί Οὐ δεῖ δὲ πᾶν πρόβλημα οὐδὲ πᾶσαν θέσιν ἐπισκοπεῖν ἀλλ᾿ ἣν ἀπορήσειεν ἄν τις τῶν λόγου δεομένων καὶ μὴ κολάσεως ἢ αἰσθήσεως οἱ μὲν γὰρ ἀποροῦντες πότερον δεῖ τοὺς θεοὺς τιμᾶν καὶ τοὺς γονέας ἀγαπᾶν ἢ οὒ κολάσεως δέονται οἱ δὲ πότερον ἡ χιὼν λευκὴ ἢ οὒ αἰσθήσεως Οὐδὲ δὴ ὧν σύνεγγυς ἡ ἀπόδειξις οὐδ᾿ ὧν λίαν πόρρω τὰ μὲν γὰρ οὐκ ἔχει ἀπορίαν τὰ δὲ πλείω ἢ κατὰ γυμναστικήν',
 'Διωρισμένων δὲ τούτων χρὴ διελέσθαι πόσα τῶν λόγων εἴδη τῶν διαλεκτικῶν Ἔστι δὲ τὸ μὲν ἐπαγωγή τὸ δὲ συλλογισμός Καὶ συλλογισμὸς μὲν τί ἐστιν εἴρηται πρότερον ἐπαγωγὴ δὲ ἡ ἀπὸ τῶν καθ᾿ ἕκαστον ἐπὶ τὰ καθόλου ἔφοδος οἷον εἰ ἔστι κυβερνήτης ὁ ἐπιστάμενος κράτιστος καὶ ἡνίοχος καὶ ὅλως ἐστὶν ὁ ἐπιστάμενος περὶ ἕκαστον ἄριστος Ἔστι δ᾿ ἡ μὲν ἐπαγωγὴ πιθανώτερον καὶ σαφέστερον καὶ κατὰ τὴν αἴσθησιν γνωριμώτερον καὶ τοῖς πολλοῖς κοινόν ὁ δὲ συλλογισμὸς βιαστικώτερον καὶ πρὸς τοὺς ἀντιλογικοὺς ἐνεργέστερον',
 'Τὰ μὲν οὖν γένη περὶ ὧν τε οἱ λόγοι καὶ ἐξ ὧν καθάπερ ἔμπροσθεν εἴρηται διωρίσθω τὰ δ᾿ ὄργανα δι᾿ ὧν εὐπορήσομεν τῶν συλλογισμῶν καὶ τῶν ἐπαγωγῶν ἐστὶ τέτταρα ἓν μὲν τὸ προτάσεις λαβεῖν δεύτερον δὲ ποσαχῶς ἕκαστον λέγεται δύνασθαι διελεῖν τρίτον τὰς διαφορὰς εὑρεῖν τέταρτον δὲ ἡ τοῦ ὁμοίου σκέψις Ἔστι δὲ τρόπον τινὰ καὶ τὰ τρία τούτων προτάσεις ἔστι γὰρ καθ᾿ ἕκαστον αὐτῶν ποιῆσαι πρότασιν οἷον ὅτι αἱρετόν ἐστι τὸ καλὸν ἢ τὸ ἡδὺ ἢ τὸ συμφέρον καὶ ὅτι διαφέρει αἴσθησις ἐπιστήμης τῷ τὴν μὲν ἀποβαλόντι δυνατὸν εἶναι πάλιν λαβεῖν τὴν δ᾿ ἀδύνατον καὶ ὅτι ὁμοίως ἔχει τὸ ὑγιεινὸν πρὸς ὑγίειαν καὶ τὸ εὐεκτικὸν πρὸς εὐεξίαν Ἔστι δ᾿ ἡ μὲν πρώτη πρότασις ἀπὸ τοῦ πολλαχῶς λεγομένου ἡ δὲ δευτέρα ἀπὸ τῶν διαφορῶν ἡ δὲ τρίτη ἀπὸ τῶν ὁμοίων',

# Combine Aligned Texts:

In [183]:
import pandas as pd

df = pd.DataFrame({
    "greek": grc_sections_clean,
    "arabic": ara_sections_clean,
    "book": pd.NA,      # fill later
    "section": pd.NA    # fill later
})

display(df)

,greek,arabic,book,section
0,ΤΟΠΙΚΩΝ Α Ἡ ΜΕΝ πρόθεσις τῆς πραγματείας μέθοδ...,غرض هذا البحث قال ان قصدنا في هذا الكتاب ان نس...,<NA>,<NA>
1,Ἑπόμενον δ᾿ ἂν εἴη τοῖς εἰρημένοις εἰπεῖν πρὸς...,فاءدة الجدل ويتبع ما وصفنا ان نذكر الاشياء الت...,<NA>,<NA>
2,Ἕξομεν δὲ τελέως τὴν μέθοδον ὅταν ὁμοίως ἔχωμε...,المهارة في الجدل وانما يحصل لنا من هذه الصناعة...,<NA>,<NA>
3,Πρῶτον οὖν θεωρητέον ἐκ τίνων ἡ μέθοδος Εἰ δὴ ...,نظرة عامة الي عناصر البرهان الجدلي فاولا ينبغي...,<NA>,<NA>
4,Λεκτέον δὲ τί ὅρος τί ἴδιον τί γένος τί συμβεβ...,دراسة عناصر الجدل تفصيلا وينبغي ان نقول ما الح...,<NA>,<NA>
...,...,...,...,...
78,Ὅσοι δὲ τῶν λόγων ψεῦδος συλλογίζονται λυτέον ...,حل الحجج الفاسدة وما كان من الاقاويل منتجا للك...,<NA>,<NA>
79,Ἐπιτίμησις δὲ λόγου κατ᾿ αὐτόν τε τὸν λόγον κα...,تبكيت الحجة وتبكيت الخصم فاما تبكيت القول في ن...,<NA>,<NA>
80,Λόγος δ᾿ ἐστὶ δῆλος ἕνα μὲν τρόπον καὶ δημοσιώ...,وضوح الحجة فساد الحجة والقول الصادق انما هو في...,<NA>,<NA>
81,Τὸ δ᾿ ἐν ἀρχῇ καὶ τὰ ἐναντία πῶς αἰτεῖται ὁ ἐρ...,المصادرة علي المطلوب الاول والمصادرة علي المتض...,<NA>,<NA>
82,Πρὸς δὲ γυμνασίαν καὶ μελέτην τῶν τοιούτων λόγ...,الارتياض في الجدل فاما ما يحتاج اليه في التخرج...,<NA>,<NA>

In [ ]:
books = [1, 1, 1, 1, 2, 2, 2]
sections = [1, 2, 3, 4, 1, 2, 3]

# df["book"] = books
# df["section"] = sections

In [189]:
import re

#this is from the above "find_all" regex code
refs = [
    '[1.1]', '[1.2]', '[1.3]', '[1.4]', '[1.5]', '[1.6]', '[1.7]', '[1.8]',
    '[1.9]', '[1.10]', '[1.11]', '[1.12]', '[1.13]', '[1.14]', '[1.15]',
    '[1.16]', '[1.17]', '[1.18]', '[2.1]', '[2.2]', '[2.3]', '[2.4]',
    '[2.5]', '[2.6]', '[2.7]', '[2.8]', '[2.9]', '[2.10]', '[2.11]',
    '[3.1]', '[3.2]', '[3.3]', '[3.4]', '[3.5]', '[3.6]', '[4.1]',
    '[4.2]', '[4.3]', '[4.4]', '[4.5]', '[4.6]', '[5.1]', '[5.2]',
    '[5.3]', '[5.4]', '[5.5]', '[5.6]', '[5.7]', '[5.8]', '[5.9]',
    '[6.1]', '[6.2]', '[6.3]', '[6.4]', '[6.5]', '[6.6]', '[6.7]',
    '[6.8]', '[6.9]', '[6.10]', '[6.11]', '[6.12]', '[6.13]', '[6.14]',
    '[7.1]', '[7.2]', '[7.3]', '[7.4]', '[7.5]', '[8.1]', '[8.2]',
    '[8.3]', '[8.4]', '[8.5]', '[8.6]', '[8.7]', '[8.8]', '[8.9]',
    '[8.10]', '[8.11]', '[8.12]', '[8.13]', '[8.14]'
]

books = []
sections = []

for ref in refs:
    book, section = map(int, re.findall(r"\d+", ref))
    books.append(book)
    sections.append(section)

df["book"] = books
df["section"] = sections

display(df)

,greek,arabic,book,section
0,ΤΟΠΙΚΩΝ Α Ἡ ΜΕΝ πρόθεσις τῆς πραγματείας μέθοδ...,غرض هذا البحث قال ان قصدنا في هذا الكتاب ان نس...,1,1
1,Ἑπόμενον δ᾿ ἂν εἴη τοῖς εἰρημένοις εἰπεῖν πρὸς...,فاءدة الجدل ويتبع ما وصفنا ان نذكر الاشياء الت...,1,2
2,Ἕξομεν δὲ τελέως τὴν μέθοδον ὅταν ὁμοίως ἔχωμε...,المهارة في الجدل وانما يحصل لنا من هذه الصناعة...,1,3
3,Πρῶτον οὖν θεωρητέον ἐκ τίνων ἡ μέθοδος Εἰ δὴ ...,نظرة عامة الي عناصر البرهان الجدلي فاولا ينبغي...,1,4
4,Λεκτέον δὲ τί ὅρος τί ἴδιον τί γένος τί συμβεβ...,دراسة عناصر الجدل تفصيلا وينبغي ان نقول ما الح...,1,5
...,...,...,...,...
78,Ὅσοι δὲ τῶν λόγων ψεῦδος συλλογίζονται λυτέον ...,حل الحجج الفاسدة وما كان من الاقاويل منتجا للك...,8,10
79,Ἐπιτίμησις δὲ λόγου κατ᾿ αὐτόν τε τὸν λόγον κα...,تبكيت الحجة وتبكيت الخصم فاما تبكيت القول في ن...,8,11
80,Λόγος δ᾿ ἐστὶ δῆλος ἕνα μὲν τρόπον καὶ δημοσιώ...,وضوح الحجة فساد الحجة والقول الصادق انما هو في...,8,12
81,Τὸ δ᾿ ἐν ἀρχῇ καὶ τὰ ἐναντία πῶς αἰτεῖται ὁ ἐρ...,المصادرة علي المطلوب الاول والمصادرة علي المتض...,8,13
82,Πρὸς δὲ γυμνασίαν καὶ μελέτην τῶν τοιούτων λόγ...,الارتياض في الجدل فاما ما يحتاج اليه في التخرج...,8,14

# Finally
we will export our data as a parquet and as a csv. 

The parquet will preserve datatypes and make our python workflow easier, while the csv is easy to share and inspect.

In [193]:
!ls

alignments  process-align.ipynb

In [198]:
df.to_parquet("alignments/aristotle_topics_parallel_doc01-doc3.parquet", index=False)
df.to_csv("alignments/aristotle_topics_parallel_doc01-doc3.csv", index=False, encoding="utf-8-sig")

In [ ]:
df = pd.read_parquet("alignments/aristotle_topics_parallel.parquet")
# df = pd.read_csv("alignments/aristotle_topics_parallel.csv", encoding="utf-8-sig")